from datetime import datetime
from typing import Protocol

from .models import Account, Position, Transaction


class PortfolioProvider(Protocol):
    async def get_accounts(self) -> list[Account]: ...
    async def get_transactions(self, account_id: str, since: datetime | None = None) -> list[Transaction]: ...
    async def get_positions(self, account_id: str) -> list[Position]: ...
    async def get_cash_balances(self, account_id: str) -> dict[str, str]: ...
