/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.beta.jsonc --include-runtime=false --strict-vars=false --env-interface=ResearchEnv worker-configuration.beta.d.ts` (hash: 26cab1f8881472ec2dfbe77a7b7f1455)
interface __BaseEnv_ResearchEnv {
	RESEARCH_ARTIFACT_BLOBS: R2Bucket;
	RESEARCH_ARTIFACT_DB: D1Database;
	RESEARCH_ARTIFACT_MODE: string;
	ZX_RUNTIME_SERVICE_TOKEN: string;
	MARKET_RESEARCH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ResearchEnv {}
}
interface ResearchEnv extends __BaseEnv_ResearchEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESEARCH_ARTIFACT_MODE" | "ZX_RUNTIME_SERVICE_TOKEN" | "MARKET_RESEARCH_TOKEN">> {}
}
