import { useState } from "react";
import type { BackupPreview } from "./backup";
import type { DailyWorkflowStep, MemoryCandidate, ReviewFeedbackRating, ReviewItemFeedback, ReviewRun, RiskDashboardData } from "./types";

const money = new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", maximumFractionDigits: 0 });

export function DailyWorkflow({ data, onStep }: { data: RiskDashboardData; onStep: (step: DailyWorkflowStep) => void }) {
  return <section className="daily-workflow"><header><div><span>今日工作台</span><h2>{data.analysisDate}</h2></div><dl><div><dt>数据更新</dt><dd>{new Date(data.receivedAt).toLocaleString("zh-CN")}</dd></div><div><dt>风险计算</dt><dd>{new Date(data.riskCalculatedAt).toLocaleString("zh-CN")}</dd></div><div><dt>复盘生成</dt><dd>{data.review.mode === "llm" ? new Date(data.review.generatedAt).toLocaleString("zh-CN") : "待生成"}</dd></div></dl></header><div className="workflow-rail">{data.workflow.map((step, index) => <button key={step.id} className={`workflow-step workflow-step--${step.status}`} onClick={() => onStep(step)}><span>{index + 1}</span><strong>{step.label}</strong><small>{step.status}</small><p>{step.detail}</p></button>)}</div></section>;
}

export function ReviewFeedbackEditor({ run, onSave }: { run: ReviewRun; onSave: (runId: string, input: { helpful: boolean | null; hasFactErrors: boolean; missingKeyFactors: boolean; note: string; itemFeedback: ReviewItemFeedback[] }) => Promise<void> }) {
  const existing = run.userFeedback;
  const [helpful, setHelpful] = useState<boolean | null>(existing?.helpful ?? null);
  const [hasFactErrors, setHasFactErrors] = useState(existing?.hasFactErrors ?? false);
  const [missingKeyFactors, setMissingKeyFactors] = useState(existing?.missingKeyFactors ?? false);
  const [note, setNote] = useState(existing?.note ?? "");
  const [items, setItems] = useState<Record<string, ReviewItemFeedback>>(Object.fromEntries((existing?.itemFeedback ?? []).map((item) => [item.reviewItemId, item])));
  const reviewItems = run.result ? [
    ...run.result.mainRisks.map((item) => ({ id: item.id, label: item.title })),
    ...run.result.planViolations.map((item) => ({ id: item.id, label: item.title })),
    ...run.result.operationReview.map((item) => ({ id: item.id, label: item.category })),
  ] : [];
  const updateItem = (id: string, patch: Partial<ReviewItemFeedback>) => setItems((current) => ({ ...current, [id]: { reviewItemId: id, rating: current[id]?.rating ?? "accurate", correction: current[id]?.correction ?? "", createdAt: current[id]?.createdAt ?? new Date().toISOString(), ...patch } }));
  return <section className="feedback-panel"><header><div><span>用户确认与纠错</span><h3>反馈只保存在本地，不自动修改规则或 Prompt。</h3></div>{existing && <strong>已保存</strong>}</header><div className="overall-feedback"><label><span>本次复盘是否有帮助</span><select value={helpful == null ? "unset" : helpful ? "yes" : "no"} onChange={(event) => setHelpful(event.target.value === "unset" ? null : event.target.value === "yes")}><option value="unset">待评价</option><option value="yes">有帮助</option><option value="no">帮助有限</option></select></label><label className="check-line"><input type="checkbox" checked={hasFactErrors} onChange={(event) => setHasFactErrors(event.target.checked)}/>存在事实错误</label><label className="check-line"><input type="checkbox" checked={missingKeyFactors} onChange={(event) => setMissingKeyFactors(event.target.checked)}/>遗漏关键因素</label></div><div className="item-feedback-list">{reviewItems.map((item) => { const feedback = items[item.id]; return <article key={item.id}><strong>{item.label}</strong><select aria-label={`${item.label} 准确度`} value={feedback?.rating ?? ""} onChange={(event) => updateItem(item.id, { rating: event.target.value as ReviewFeedbackRating })}><option value="">未评价</option><option value="accurate">准确</option><option value="partially-accurate">部分准确</option><option value="incorrect">错误</option><option value="missing-context">缺少上下文</option></select><textarea aria-label={`${item.label} 修正说明`} value={feedback?.correction ?? ""} placeholder="可选：补充事实或修正说明" onChange={(event) => updateItem(item.id, { correction: event.target.value })}/></article>; })}</div><label className="feedback-note"><span>用户补充说明</span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="只保存为候选上下文，需在候选区再次接受或拒绝。"/></label><button className="primary-action" onClick={() => void onSave(run.id, { helpful, hasFactErrors, missingKeyFactors, note, itemFeedback: Object.values(items).filter((item) => Boolean(item.rating)) })}>保存本次反馈</button></section>;
}

export function ReviewHistory({ runs }: { runs: ReviewRun[] }) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const selected = runs.find((run) => run.id === selectedId) ?? null;
  return <section className="review-history"><header><div><span>历史复盘</span><h3>每次运行使用当时冻结的数据。</h3></div><strong>{runs.length} 条</strong></header>{selected ? <div className="frozen-review"><button onClick={() => setSelectedId(null)}>返回历史列表</button><h3>{selected.reviewDate} · {selected.status}</h3><p>{selected.result?.summary ?? "模型分析失败；仅保留确定性风险快照。"}</p><dl><div><dt>当日盈亏</dt><dd>{money.format(selected.riskSnapshot.portfolio.dayPnl)}</dd></div><div><dt>风险事件</dt><dd>{selected.riskSnapshot.events.length}</dd></div><div><dt>规则 / Evidence</dt><dd>{selected.riskRuleVersion} / {selected.evidenceSchemaVersion}</dd></div><div><dt>模型</dt><dd>{selected.provider}/{selected.model}</dd></div><div><dt>Prompt</dt><dd>{selected.promptVersion}</dd></div><div><dt>证据数量</dt><dd>{selected.evidencePack.evidence.length}</dd></div></dl><details><summary>冻结的 Risk Snapshot</summary>{selected.riskSnapshot.metrics.map((item) => <p key={item.id}>{item.label}：{item.value ?? "—"} · {item.reliable ? "可靠" : "受限"}</p>)}{selected.riskSnapshot.events.map((item) => <p key={item.id}>{item.title} · {item.severity}</p>)}</details><details><summary>冻结的 Evidence Pack</summary>{selected.evidencePack.evidence.map((item) => <p key={item.id}>{item.id} · {item.source}</p>)}</details>{selected.result?.limitations.map((item) => <p className="data-warning" key={item}>{item}</p>)}{selected.warnings.map((item) => <p className="data-warning" key={item}>{item}</p>)}{selected.errors.map((item) => <p className="data-warning" key={item}>{item}</p>)}{selected.userFeedback && <p>用户补充：{selected.userFeedback.note || "无文字补充"}</p>}</div> : <div className="history-list">{runs.map((run) => <button key={run.id} onClick={() => setSelectedId(run.id)}><span><strong>{run.reviewDate}</strong><small>{new Date(run.createdAt).toLocaleString("zh-CN")}</small></span><span>{money.format(run.riskSnapshot.portfolio.dayPnl)}<small>{run.riskSnapshot.events.length} 个事件</small></span><span>{run.status}<small>{run.userFeedback?.helpful == null ? "未评价" : run.userFeedback.helpful ? "有帮助" : "帮助有限"}</small></span><span>{run.provider}/{run.model}</span></button>)}</div>}</section>;
}

export function MemoryCandidates({ items, onStatus }: { items: MemoryCandidate[]; onStatus: (id: string, status: "accepted" | "rejected") => Promise<void> }) {
  return <section className="memory-panel"><header><div><span>Memory Candidate</span><h3>接受后仍只保存在本地，不注入 LLM。</h3></div><strong>{items.filter((item) => item.status === "pending").length} 待审核</strong></header>{items.length ? items.map((item) => <article key={item.id}><div><span>{item.category}</span><small>{item.status}</small></div><p>{item.content}</p><footer><button disabled={item.status === "accepted"} onClick={() => void onStatus(item.id, "accepted")}>接受</button><button disabled={item.status === "rejected"} onClick={() => void onStatus(item.id, "rejected")}>拒绝</button></footer></article>) : <p className="empty-note">填写明确纠错或补充后，这里会出现待审核候选。</p>}</section>;
}

export function DiagnosticsPanel({ data }: { data: RiskDashboardData }) {
  const { market, portfolio, risk, llm } = data.diagnostics;
  const groups = [
    { title: "Market", rows: [["Provider", market.provider], ["最后成功", market.lastSuccessAt ?? "—"], ["最后失败", market.lastFailureAt ?? "—"], ["耗时", market.requestDurationMs == null ? "—" : `${market.requestDurationMs} ms`], ["数据时间", market.dataTimestamp ?? "—"], ["stale", String(market.stale)], ["warnings", market.warnings.join("；") || "—"], ["errors", market.errors.join("；") || "—"]] },
    { title: "Portfolio", rows: [["最近导入", portfolio.lastImportAt ?? "—"], ["成功 / 重复 / 失败", `${portfolio.successRows} / ${portfolio.duplicateRows} / ${portfolio.failedRows}`], ["未识别标的", portfolio.unknownInstruments.join("、") || "—"], ["对账差异", String(portfolio.reconciliationDifferences)]] },
    { title: "Risk Engine", rows: [["执行时间", risk.executedAt], ["耗时", `${risk.durationMs} ms`], ["持仓 / 规则", `${risk.inputPositionCount} / ${risk.ruleCount}`], ["触发事件", String(risk.triggeredEventCount)], ["受阻指标", String(risk.blockedMetricCount)], ["异常", risk.errors.join("；") || "—"]] },
    { title: "LLM Gateway", rows: [["Provider / Model", llm.provider ? `${llm.provider}/${llm.model}` : "—"], ["fallback path", llm.fallbackPath.join(" → ") || "—"], ["Prompt", llm.promptVersion], ["耗时", llm.requestDurationMs == null ? "—" : `${llm.requestDurationMs} ms`], ["tokens", `${llm.inputTokens ?? "—"} / ${llm.outputTokens ?? "—"}`], ["estimated cost", llm.estimatedCost == null ? "—" : String(llm.estimatedCost)], ["Schema", llm.schemaValidation], ["重试", llm.retryCount == null ? "—" : String(llm.retryCount)], ["最终错误", llm.finalError ?? "—"]] },
  ];
  return <section className="diagnostics-panel"><header><span>Diagnostics</span><h3>最近一次执行，不记录凭据或完整请求。</h3></header><div>{groups.map((group) => <details key={group.title}><summary>{group.title}</summary><dl>{group.rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details>)}</div></section>;
}

export function BackupPanel({ onExport, onPreview, onRestore }: { onExport: () => { filename: string; content: string }; onPreview: (text: string) => BackupPreview; onRestore: (preview: BackupPreview, mode: "merge" | "overwrite") => Promise<void> }) {
  const [preview, setPreview] = useState<BackupPreview | null>(null);
  const [error, setError] = useState<string | null>(null);
  const download = () => { const output = onExport(); const url = URL.createObjectURL(new Blob([output.content], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = output.filename; anchor.click(); URL.revokeObjectURL(url); };
  return <section className="backup-panel"><h3>本地完整备份</h3><p>包含账本、规则元数据、复盘、反馈、Memory Candidate 和设置；不包含 API Key。</p><button className="primary-action" onClick={download}>导出 JSON 备份</button><label className="file-picker"><strong>选择备份文件并预览</strong><input type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; void file.text().then((text) => { try { setPreview(onPreview(text)); setError(null); } catch (reason) { setPreview(null); setError(reason instanceof Error ? reason.message : "备份无效"); } }); }}/></label>{error && <p className="data-warning">{error}</p>}{preview && <div className="backup-preview"><p>交易 {preview.counts.transactions} · 复盘 {preview.counts.reviews} · 反馈 {preview.counts.feedback} · 候选 {preview.counts.memories}</p><p>冲突：交易 {preview.conflicts.transactions} · 复盘 {preview.conflicts.reviews} · 反馈 {preview.conflicts.feedback} · 候选 {preview.conflicts.memories}</p><div><button onClick={() => void onRestore(preview, "merge")}>合并导入</button><button className="danger-action" onClick={() => window.confirm("覆盖将替换当前本地 Risk 数据，是否继续？") && void onRestore(preview, "overwrite")}>覆盖恢复</button></div></div>}</section>;
}
