import { useEffect, useMemo, useRef, useState } from "react";
import type { BackupPreview } from "./backup";
import { DEFAULT_CSV_MAPPING } from "./csv";
import { BackupPanel, DailyWorkflow, DiagnosticsPanel, MemoryCandidates, ReviewFeedbackEditor, ReviewHistory } from "./RiskDogfoodPanels";
import { useRiskWorkspace } from "./useRiskWorkspace";
import type { CsvFieldMapping, CsvPreview, DailyWorkflowStep, EvidenceItem, HoldingParseDraft, Position, ReviewItemFeedback, RiskDashboardData, RiskEvent } from "./types";

type View = "dashboard" | "positions" | "activity" | "review" | "settings";
const navItems: Array<{ id: View; label: string }> = [{ id: "dashboard", label: "总览" }, { id: "positions", label: "持仓" }, { id: "activity", label: "记录" }, { id: "review", label: "复盘" }, { id: "settings", label: "设置" }];
const money = new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", maximumFractionDigits: 0 });
const number = new Intl.NumberFormat("zh-CN", { maximumFractionDigits: 3 });
const pct = (value: number | null) => value == null ? "—" : `${(value * 100).toFixed(1)}%`;
const value = (input: number | null, digits = 3) => input == null ? "—" : input.toFixed(digits);
const confidence = (input: number) => input >= 0.85 ? "高" : input >= 0.65 ? "中" : "低";
const marketUnavailable = (data: RiskDashboardData) => data.dataMode === "api" && (Boolean(data.diagnostics.market.errors.length) || data.sourceHealth.some((source) => source.name === "ApiMarketDataProvider" && source.status === "offline"));
const marketModeLabel = (data: RiskDashboardData) => data.dataMode === "mock" ? "Mock 测试行情" : marketUnavailable(data) ? "API 行情不可用" : "真实 API 行情";
const marketFailureDetail = (data: RiskDashboardData) => data.diagnostics.market.errors[0] ?? data.sourceHealth.find((source) => source.name === "ApiMarketDataProvider")?.freshness ?? "全部行情上游不可用";
const marketStatusDetail = (data: RiskDashboardData) => marketUnavailable(data) ? marketFailureDetail(data) : data.sourceHealth.find((source) => source.name === "ApiMarketDataProvider" || source.name === "MockMarketDataProvider")?.freshness ?? (data.reconciliation.unresolved ? "对账待处理" : "已对账");
const reliableDetail = (data: RiskDashboardData) => data.diagnostics.market.snapshotStatus === "closed-snapshot" ? "交易与对账通过质量检查，行情按闭市快照用于复盘。" : "交易、对账与报价通过质量检查。";
const quoteQualityLabel = (position: Position, data: RiskDashboardData) => data.diagnostics.market.snapshotStatus === "closed-snapshot" && position.quoteQuality === "stale" ? "闭市快照" : position.quoteQuality === "live" ? "实时" : position.quoteQuality === "cached" ? "缓存" : position.quoteQuality === "unavailable" ? "不可用" : "盘中过期";
const quoteQualityClass = (position: Position, data: RiskDashboardData) => data.diagnostics.market.snapshotStatus === "closed-snapshot" && position.quoteQuality === "stale" ? "live" : position.quoteQuality;

function Metric({ label, value, note, tone = "neutral" }: { label: string; value: string; note: string; tone?: "neutral" | "danger" | "warning" }) { return <article className={`risk-metric risk-metric--${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }

function ReliabilityBand({ data }: { data: RiskDashboardData }) {
  return <div className={`reliability-band ${data.portfolio.reliable ? "is-reliable" : "is-blocked"}`}><span className="reliability-band__signal" aria-hidden="true"/><div><strong>{data.portfolio.reliable ? "风险快照可可靠计算" : "风险结果已降低可信度"}</strong><p>{data.portfolio.reliable ? reliableDetail(data) : data.dataWarnings.slice(0, 3).join("；") || "存在未解决的数据质量问题。"}</p></div><span className="reliability-band__time">更新 {new Date(data.receivedAt).toLocaleTimeString("zh-CN")}</span></div>;
}

function ExposureChart({ data }: { data: RiskDashboardData }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!ref.current) return; let chart: import("echarts/core").EChartsType | undefined; let disposed = false; const resize = () => chart?.resize(); void import("./chart").then(({ createEquityChart }) => { if (!ref.current || disposed) return; chart = createEquityChart(ref.current, data.equityCurve); window.addEventListener("resize", resize); }); return () => { disposed = true; window.removeEventListener("resize", resize); chart?.dispose(); }; }, [data]);
  return <div ref={ref} className="exposure-chart" role="img" aria-label="账户净值曲线"/>;
}

function AlertCard({ event, onEvidence }: { event: RiskEvent; onEvidence: (id: string) => void }) { return <article className={`alert-card alert-card--${event.severity}`}><div className="alert-card__top"><span className="alert-card__severity">{event.severity}</span><span>{event.triggeredAt.slice(11, 16)}</span></div><h3>{event.title}</h3><p>{event.message}</p><div className="alert-card__evidence">{event.evidenceIds.slice(0, 2).map((id) => <button key={id} onClick={() => onEvidence(id)}>{id}</button>)}</div></article>; }

function PositionTable({ data }: { data: RiskDashboardData }) {
  return <div className="position-table-wrap"><table className="position-table"><thead><tr><th>标的</th><th>现价 / 质量</th><th>数量</th><th>市值</th><th>浮动盈亏</th><th>名义仓位</th><th>有效敞口</th><th>交易计划</th></tr></thead><tbody>{data.positions.length ? data.positions.map((position) => <tr key={position.instrumentId}><td><div className="instrument-cell"><strong>{position.name}</strong><span>{position.instrumentId} · {position.industry}</span></div></td><td><strong>{value(position.price)}</strong><span className={`quality-tag quality-tag--${quoteQualityClass(position, data)}`}>{quoteQualityLabel(position, data)} · {position.quoteTime}</span></td><td>{number.format(position.quantity)}</td><td>{position.marketValue == null ? "—" : money.format(position.marketValue)}</td><td className={(position.unrealizedPnl ?? 0) >= 0 ? "is-positive" : "is-negative"}>{position.unrealizedPnl == null ? "—" : money.format(position.unrealizedPnl)}</td><td>{pct(position.nominalWeight)}</td><td><strong>{pct(position.effectiveExposure)}</strong>{position.leverageMultiplier > 1 && <span className="leverage-mark">×{position.leverageMultiplier}</span>}</td><td><span className={`plan-state plan-state--${position.planStatus}`}>{position.planStatus === "aligned" ? "符合" : position.planStatus === "overweight" ? "超计划" : "缺失"}</span></td></tr>) : <tr><td colSpan={8} className="empty-cell">尚无交易推导出的持仓</td></tr>}</tbody></table></div>;
}

function Dashboard({ data, onEvidence, onNavigate, onWorkflow }: { data: RiskDashboardData; onEvidence: (id: string) => void; onNavigate: (view: View) => void; onWorkflow: (step: DailyWorkflowStep) => void }) {
  const highEvents = data.riskEvents.filter((event) => event.severity === "high" || event.severity === "critical");
  return <div className="risk-view risk-dashboard"><DailyWorkflow data={data} onStep={onWorkflow}/><ReliabilityBand data={data}/><div className="data-mode-strip"><span>数据模式 <strong>{marketModeLabel(data)}</strong></span><span>账本 {data.transactions.length} 条</span><span>对账 <strong>{data.reconciliation.unresolved ? "待处理" : "一致"}</strong></span></div><section className="risk-metric-grid" aria-label="账户风险指标"><article className="risk-overview-card"><div className="risk-overview-card__head"><span>账户净值</span><span>本地账本</span></div><strong>{money.format(data.portfolio.netValue)}</strong><p className={data.portfolio.dayPnl >= 0 ? "is-positive" : "is-negative"}>今日 {money.format(data.portfolio.dayPnl)} · {pct(data.portfolio.dayReturn)}</p><ExposureChart data={data}/></article><Metric label="有效总敞口" value={pct(data.portfolio.effectiveExposure)} note="规则上限 120%" tone="danger"/><Metric label="持仓市值" value={money.format(data.portfolio.marketValue)} note={`${data.positions.length} 个交易推导持仓`}/><Metric label="当前回撤" value={pct(data.portfolio.currentDrawdown)} note={`历史最大 ${pct(data.portfolio.maxDrawdown)}`} tone="warning"/><Metric label="可用现金" value={money.format(data.portfolio.cash)} note="由现金与交易事件推导"/></section><section className="risk-section"><header className="risk-section__header"><div><p>需要先处理的事实</p><h2>{highEvents.length} 个高优先级事件正在生效。</h2></div><button onClick={() => onNavigate("activity")}>查看完整时间线</button></header><div className="alert-grid">{highEvents.map((event) => <AlertCard key={event.id} event={event} onEvidence={onEvidence}/>)}</div></section><section className="risk-section"><header className="risk-section__header"><div><p>仓位与计划</p><h2>所有仓位都由追加式交易账本重建。</h2></div><button onClick={() => onNavigate("positions")}>展开持仓与对账</button></header><PositionTable data={data}/></section></div>;
}

function Reconciliation({ data, onSave }: { data: RiskDashboardData; onSave: (id: string, quantity: number, cost: number | null) => Promise<void> }) {
    const [drafts, setDrafts] = useState<Record<string, { quantity: string; cost: string }>>({});
    return <section className="reconciliation-card"><header><div><span>券商对账</span><h3>{data.reconciliation.unresolved ? "存在未确认差异" : "交易账本与券商数量一致"}</h3></div><strong>{data.reconciliation.items.filter((item) => item.status !== "matched").length} 项待处理</strong></header><div className="position-table-wrap"><table className="position-table"><thead><tr><th>标的</th><th>交易推导数量</th><th>券商数量 / 成本</th><th>数量差异</th><th>成本差异</th><th>状态</th></tr></thead><tbody>{data.reconciliation.items.map((item) => { const draft = drafts[item.instrumentId] ?? { quantity: item.brokerQuantity?.toString() ?? "", cost: item.brokerAverageCost?.toString() ?? "" }; return <tr key={item.instrumentId}><td>{item.name}</td><td>{number.format(item.derivedQuantity)}</td><td><div className="reconcile-input"><input aria-label={`${item.name} 券商数量`} inputMode="decimal" value={draft.quantity} placeholder="当前数量" onChange={(event) => setDrafts({ ...drafts, [item.instrumentId]: { ...draft, quantity: event.target.value } })}/><input aria-label={`${item.name} 券商成本`} inputMode="decimal" value={draft.cost} placeholder="平均成本（可选）" onChange={(event) => setDrafts({ ...drafts, [item.instrumentId]: { ...draft, cost: event.target.value } })}/><button disabled={!draft.quantity || !Number.isFinite(Number(draft.quantity)) || Boolean(draft.cost && !Number.isFinite(Number(draft.cost)))} onClick={() => void onSave(item.instrumentId, Number(draft.quantity), draft.cost ? Number(draft.cost) : null)}>保存</button></div></td><td>{item.quantityDifference == null ? "未核对" : number.format(item.quantityDifference)}</td><td>{item.costDifference == null ? "—" : value(item.costDifference)}</td><td><span className={`quality-tag quality-tag--${item.status === "matched" ? "live" : "stale"}`}>{item.status === "matched" ? "一致" : item.status === "mismatch" ? "差异" : "未验证"}</span></td></tr>; })}</tbody></table></div>{data.reconciliation.anomalies.map((item) => <p className="data-warning" key={item.id}>{item.message}</p>)}</section>;
}

function PositionFactGrid({ data }: { data: RiskDashboardData }) {
  const brokerCount = data.brokerSnapshot?.positions.length ?? data.reconciliation.items.filter((item) => item.brokerQuantity != null).length;
  return <section className="position-fact-grid"><article><span>账本推导</span><strong>{data.positions.length} 个持仓</strong><p>{data.transactions.length} 条交易事件按时间顺序重建，不被券商快照覆盖。</p></article><article><span>券商快照</span><strong>{brokerCount ? `${brokerCount} 个标的` : "待确认"}</strong><p>{data.brokerSnapshot ? `${data.brokerSnapshot.accountName ?? "未命名账户"} · ${new Date(data.brokerSnapshot.snapshotAt).toLocaleString("zh-CN")}` : "可粘贴券商持仓文本或 CSV 生成草稿。"}</p></article><article><span>行情估值</span><strong>{marketModeLabel(data)}</strong><p>{marketStatusDetail(data)}</p></article></section>;
}

function Positions({ data, onSaveBroker, onOpenHoldingsPaste }: { data: RiskDashboardData; onSaveBroker: (id: string, quantity: number, cost: number | null) => Promise<void>; onOpenHoldingsPaste: () => void }) { return <div className="risk-view"><header className="view-intro review-intro"><div><p>交易重建持仓</p><h2>账本是事实，券商快照只用于对账。</h2><span>买入、卖出、费用、税费与 adjustment 均按时间顺序处理；确认后的券商持仓不会改交易账本。</span></div><button onClick={onOpenHoldingsPaste}>粘贴券商持仓</button></header><PositionFactGrid data={data}/><PositionTable data={data}/><Reconciliation data={data} onSave={onSaveBroker}/><div className="position-detail-grid">{data.positions.map((position) => <article key={position.instrumentId}><div><span>{position.symbol}</span><span>{position.industry}</span></div><h3>{position.name}</h3><p>{position.themes.join(" / ")}</p><dl><div><dt>平均成本</dt><dd>{value(position.averageCost)}</dd></div><div><dt>已实现盈亏</dt><dd>{money.format(position.realizedPnl)}</dd></div><div><dt>费用 / 税费</dt><dd>{money.format(position.fees + position.taxes)}</dd></div><div><dt>账本证据</dt><dd>{position.transactionEvidenceIds.length}</dd></div></dl></article>)}</div></div>; }

function Activity({ data, onEvidence }: { data: RiskDashboardData; onEvidence: (id: string) => void }) { return <div className="risk-view"><header className="view-intro"><p>追加式交易账本</p><h2>{data.transactions.length} 条真实或 Mock 交易事件。</h2><span>更正通过新的 POSITION_ADJUSTMENT 事件完成，历史不会被覆盖。</span></header><div className="activity-list">{data.activity.map((item) => <button key={item.id} className={`activity-row activity-row--${item.tone}`} onClick={() => onEvidence(item.evidenceId)}><time>{item.time}</time><span className="activity-row__marker"/><div><span>{item.type}</span><h3>{item.title}</h3><p>{item.detail}</p></div><code>{item.evidenceId}</code></button>)}</div></div>; }

function Review({ data, onEvidence, onGenerate, onSaveFeedback, onMemoryStatus, loading, error }: { data: RiskDashboardData; onEvidence: (id: string) => void; onGenerate: () => Promise<void>; onSaveFeedback: (runId: string, input: { helpful: boolean | null; hasFactErrors: boolean; missingKeyFactors: boolean; note: string; itemFeedback: ReviewItemFeedback[] }) => Promise<void>; onMemoryStatus: (id: string, status: "accepted" | "rejected") => Promise<void>; loading: boolean; error: string | null }) {
  const review = data.review;
  const source = review.mode === "llm" ? `${review.provider}/${review.model}` : review.fallbackReason ? "Mock 降级" : "Mock Review";
  const currentRun = data.reviewRuns.find((run) => run.reviewDate === data.analysisDate && run.result?.evidencePackFingerprint === review.evidencePackFingerprint);
  return <div className="risk-view"><header className="view-intro review-intro"><div><p>Evidence Pack 驱动复盘</p><h2>{review.mode === "llm" ? "真实 LLM 只解释本轮结构化证据。" : "先确定性计算，再按需生成真实复盘。"}</h2><span>{source} · {new Date(review.generatedAt).toLocaleString("zh-CN")} · {data.evidencePack.reliable ? "可靠" : "可信度降低"}</span></div><button disabled={loading} onClick={() => void onGenerate()}>{loading ? "正在生成…" : review.mode === "llm" ? "重新生成真实复盘" : "生成真实复盘"}</button></header>{error && <p className="review-status review-status--warning" role="status">{error}</p>}{review.mode === "llm" && <p className="review-status" role="status">已通过项目 LLM 网关生成{review.fallbackIndex ? `，使用第 ${review.fallbackIndex + 1} 个候选模型` : "，主候选模型成功"}。完整运行已冻结到本地存档。</p>}<section className="review-summary"><span>今日摘要</span><p>{review.summary}</p></section><div className="review-columns"><section><header><span>主要风险</span><strong>{review.mainRisks.length}</strong></header>{review.mainRisks.map((risk) => <article key={risk.id} className={`review-risk review-risk--${risk.severity}`}><h3>{risk.title}</h3><p>{risk.explanation}</p><div>{risk.evidenceIds.map((id) => <button key={id} onClick={() => onEvidence(id)}>{id}</button>)}</div></article>)}</section><section><header><span>计划与操作偏离</span><strong>{review.planViolations.length + review.operationReview.length}</strong></header>{[...review.planViolations.map((item) => ({ id: item.id, title: item.title, detail: item.detail, evidenceIds: item.evidenceIds })), ...review.operationReview.map((item) => ({ id: item.id, title: item.category, detail: item.observation, evidenceIds: item.evidenceIds }))].map((item) => <article key={item.id}><h3>{item.title}</h3><p>{item.detail}</p><div>{item.evidenceIds.map((id) => <button key={id} onClick={() => onEvidence(id)}>{id}</button>)}</div></article>)}</section></div><div className="review-footer-grid"><section><span>反事实问题</span>{review.counterfactuals.map((item) => <p key={item}>{item}</p>)}</section><section><span>未知与限制</span>{[...review.unknowns, ...review.limitations].map((item) => <p key={item}>{item}</p>)}</section></div>{currentRun && <ReviewFeedbackEditor key={`${currentRun.id}-${currentRun.userFeedback?.updatedAt ?? "new"}`} run={currentRun} onSave={onSaveFeedback}/>}<MemoryCandidates items={data.memoryCandidates} onStatus={onMemoryStatus}/><ReviewHistory runs={data.reviewRuns}/></div>;
}

function Settings({ data, onMode, onImport, onClear, onRestore, onExportBackup, onPreviewBackup, onRestoreBackup }: { data: RiskDashboardData; onMode: (mode: "mock" | "api") => Promise<void>; onImport: () => void; onClear: () => Promise<void>; onRestore: () => Promise<void>; onExportBackup: () => { filename: string; content: string }; onPreviewBackup: (text: string) => BackupPreview; onRestoreBackup: (preview: BackupPreview, mode: "merge" | "overwrite") => Promise<void> }) { return <div className="risk-view"><header className="view-intro"><p>数据与运行边界</p><h2>Provider 可替换，账本始终留在浏览器本地。</h2><span>真实 LLM 仅在手动生成复盘时读取结构化 Evidence Pack；不会获得交易权限。</span></header><div className="settings-grid"><section><h3>风险规则</h3>{[["最大有效敞口", "120%"], ["单标的上限", "35%"], ["主题集中度", "45%"], ["盘中行情新鲜度", "120 秒"]].map(([label, setting]) => <div className="setting-row" key={label}><span>{label}</span><strong>{setting}</strong></div>)}</section><section><h3>数据源</h3>{data.sourceHealth.map((source) => <div className="setting-row" key={source.name}><span><i className={`source-dot source-dot--${source.status}`}/>{source.name}</span><strong>{source.freshness}</strong></div>)}</section><section><h3>行情 Provider</h3><button className="mode-toggle" aria-pressed={data.dataMode === "api"} onClick={() => void onMode(data.dataMode === "mock" ? "api" : "mock")}><span><strong>{data.dataMode === "mock" ? "MockMarketDataProvider（测试）" : marketUnavailable(data) ? "ApiMarketDataProvider（不可用）" : "ApiMarketDataProvider（真实）"}</strong><small>{data.dataMode === "mock" ? "用户显式选择的本地可重复场景" : marketStatusDetail(data)}</small></span><i/></button><div className="setting-row"><span>Review Service</span><strong>{data.review.mode === "llm" ? "Project AI Gateway" : data.review.fallbackReason ? "Mock 降级" : "Mock / 手动 LLM"}</strong></div></section><section className="data-actions"><h3>CSV 数据管理</h3><button className="primary-action" onClick={onImport}>导入交易 CSV</button><a href="/assets/risk/sample-transactions.csv" download>下载测试 CSV</a><button onClick={() => void onRestore()}>恢复 Mock 数据</button><button className="danger-action" onClick={() => window.confirm("确认清空浏览器本地交易、对账、复盘、反馈和候选记录？") && void onClear()}>清空本地数据</button></section><BackupPanel onExport={onExportBackup} onPreview={onPreviewBackup} onRestore={onRestoreBackup}/></div><DiagnosticsPanel data={data}/></div>; }

function CsvImportDialog({ existingCount, preview, mapping, onMapping, onPreview, onImport, onClose }: { existingCount: number; preview: CsvPreview | null; mapping: CsvFieldMapping; onMapping: (mapping: CsvFieldMapping) => void; onPreview: (text: string) => void; onImport: () => Promise<void>; onClose: () => void }) {
  const [fileName, setFileName] = useState(""); const fields = Object.keys(mapping) as Array<keyof CsvFieldMapping>;
  return <div className="evidence-layer" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="import-drawer" role="dialog" aria-modal="true" aria-labelledby="import-title"><button className="evidence-close" onClick={onClose}>关闭</button><span>浏览器本地解析</span><h2 id="import-title">导入交易 CSV</h2><p>当前账本 {existingCount} 条。合法行追加保存，错误行不会阻止导入。</p><label className="file-picker"><strong>{fileName || "选择 CSV 文件"}</strong><input type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); void file.text().then(onPreview); }}/></label>{preview && <><div className="mapping-grid">{fields.map((field) => <label key={field}><span>{field}</span><select value={mapping[field]} onChange={(event) => onMapping({ ...mapping, [field]: event.target.value })}>{preview.headers.map((header) => <option key={header}>{header}</option>)}</select></label>)}</div><div className="import-stats"><span>可导入 <strong>{preview.valid.length}</strong></span><span>错误 <strong>{preview.invalid.length}</strong></span><span>重复 <strong>{preview.duplicates.length}</strong></span></div><div className="import-preview"><table><thead><tr><th>ID</th><th>事件</th><th>标的</th><th>数量</th><th>时间</th></tr></thead><tbody>{preview.valid.slice(0, 8).map((item) => <tr key={item.id}><td>{item.id}</td><td>{item.type}</td><td>{item.instrumentId ?? "—"}</td><td>{item.quantity}</td><td>{item.executedAt}</td></tr>)}</tbody></table>{preview.invalid.map((item) => <p className="data-warning" key={item.rowNumber}>第 {item.rowNumber} 行：{item.errors.join("；")}</p>)}{preview.duplicates.map((item) => <p className="duplicate-note" key={`${item.rowNumber}-${item.id}`}>第 {item.rowNumber} 行 {item.id}：{item.reason}</p>)}</div><button className="primary-action" disabled={!preview.valid.length} onClick={() => void onImport()}>追加导入 {preview.valid.length} 条</button></>}</aside></div>;
}

function HoldingsParseDialog({ loading, error, onParse, onConfirm, onClose }: { loading: boolean; error: string | null; onParse: (text: string, sourceKind: "csv" | "text") => Promise<HoldingParseDraft | null>; onConfirm: (draft: HoldingParseDraft) => Promise<void>; onClose: () => void }) {
  const [text, setText] = useState("");
  const [sourceKind, setSourceKind] = useState<"csv" | "text">("text");
  const [draft, setDraft] = useState<HoldingParseDraft | null>(null);
  const confirmable = draft?.positions.filter((item) => item.instrumentId && item.quantity != null && item.confidence >= 0.55) ?? [];
  return <div className="evidence-layer" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="import-drawer holdings-drawer" role="dialog" aria-modal="true" aria-labelledby="holdings-title"><button className="evidence-close" onClick={onClose}>关闭</button><span>LLM 草稿解析</span><h2 id="holdings-title">粘贴券商持仓</h2><p>输入文本或 CSV 后生成可确认草稿。确认只更新券商快照与对账数量，不修改交易账本。</p><div className="holdings-source"><button className={sourceKind === "text" ? "is-active" : ""} onClick={() => setSourceKind("text")}>文本</button><button className={sourceKind === "csv" ? "is-active" : ""} onClick={() => setSourceKind("csv")}>CSV</button></div><textarea className="holdings-textarea" value={text} placeholder={"示例：\n证券代码,证券名称,持仓数量,成本价,市值\n512480,半导体ETF,10000,0.92,9300"} onChange={(event) => setText(event.target.value)}/><button className="primary-action" disabled={loading || !text.trim()} onClick={async () => setDraft(await onParse(text, sourceKind))}>{loading ? "解析中…" : "生成解析草稿"}</button>{error && <p className="data-warning">{error}</p>}{draft && <section className="holdings-draft"><header><div><span>解析草稿</span><h3>{draft.accountName ?? "未命名账户"} · {new Date(draft.snapshotAt).toLocaleString("zh-CN")}</h3></div><strong>{confirmable.length} 个可确认</strong></header><div className="import-preview"><table><thead><tr><th>标的</th><th>数量</th><th>成本</th><th>置信度</th><th>提示</th></tr></thead><tbody>{draft.positions.map((item, index) => <tr key={`${item.instrumentId ?? item.rawSymbol ?? "row"}-${index}`}><td>{item.instrumentId ?? item.rawSymbol ?? item.rawName ?? "未知"}</td><td>{item.quantity == null ? "—" : number.format(item.quantity)}</td><td>{item.averageCost == null ? "—" : value(item.averageCost)}</td><td>{confidence(item.confidence)} · {Math.round(item.confidence * 100)}%</td><td>{item.warnings.join("；") || "—"}</td></tr>)}</tbody></table></div>{draft.unresolvedRows.map((item) => <p className="data-warning" key={`${item.rowNumber}-${item.raw}`}>第 {item.rowNumber ?? "?"} 行：{item.reason}</p>)}{draft.warnings.map((item) => <p className="duplicate-note" key={item}>{item}</p>)}<button className="primary-action" disabled={!confirmable.length} onClick={async () => { await onConfirm(draft); onClose(); }}>确认保存券商快照</button></section>}</aside></div>;
}

function EvidenceDrawer({ evidence, onClose }: { evidence: EvidenceItem | undefined; onClose: () => void }) { if (!evidence) return null; return <div className="evidence-layer" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="evidence-drawer" role="dialog" aria-modal="true" aria-labelledby="evidence-title"><button className="evidence-close" onClick={onClose}>关闭</button><span>{evidence.type}</span><h2 id="evidence-title">{evidence.title}</h2><p>{evidence.id}</p><dl><div><dt>时间</dt><dd>{evidence.timestamp}</dd></div><div><dt>来源</dt><dd>{evidence.source}</dd></div>{Object.entries(evidence.payload).map(([key, item]) => <div key={key}><dt>{key}</dt><dd>{String(item)}</dd></div>)}</dl></aside></div>; }

export default function RiskWorkbench() {
  const workspace = useRiskWorkspace(); const [view, setView] = useState<View>("dashboard"); const [selectedEvidence, setSelectedEvidence] = useState<string>(); const [importOpen, setImportOpen] = useState(false); const [holdingsOpen, setHoldingsOpen] = useState(false); const [csvText, setCsvText] = useState(""); const [mapping, setMapping] = useState(DEFAULT_CSV_MAPPING); const preview = useMemo(() => csvText ? workspace.previewCsv(csvText, mapping) : null, [csvText, mapping, workspace.data]);
  useEffect(() => { if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; let cleanup = () => {}; void Promise.all([import("gsap"), import("gsap/ScrollTrigger")]).then(([module, trigger]) => { const gsap = module.default; gsap.registerPlugin(trigger.ScrollTrigger); const context = gsap.context(() => gsap.from(".risk-hero > div:first-child > *", { y: 32, opacity: 0, duration: 0.8, stagger: 0.08, ease: "power3.out" })); cleanup = () => context.revert(); }); return () => cleanup(); }, [view]);
  if (workspace.loading && !workspace.data) return <div className="risk-loading">正在从本地账本重建风险工作区…</div>;
  if (!workspace.data) return <div className="risk-loading">{workspace.error ?? "工作区暂不可用"}</div>;
  const data = workspace.data;
  const evidence = data.evidence.find((item) => item.id === selectedEvidence);
  const openEvidence = (id: string) => { if (data.evidence.some((item) => item.id === id)) setSelectedEvidence(id); };
  const runWorkflow = (step: DailyWorkflowStep) => {
    if (step.id === "transactions") setImportOpen(true);
    else if (step.id === "reconciliation") setView("positions");
    else if (step.id === "market" || step.id === "risk") void workspace.reload();
    else if (step.id === "review") setView("review");
    else if (step.id === "complete") { if (data.reviewRuns.some((run) => run.reviewDate === data.analysisDate)) void workspace.completeToday(); else setView("review"); }
  };
  return <div className="risk-app"><header className="risk-appbar"><a href="/lab" className="risk-brand"><span className="risk-brand__mark">Z</span><span><strong>持仓风险台</strong><small>Evidence before narrative</small></span></a><nav aria-label="风险工作台导航">{navItems.map((item) => <button key={item.id} className={view === item.id ? "is-active" : ""} onClick={() => setView(item.id)}>{item.label}</button>)}</nav><div className="risk-appbar__actions"><a className="risk-appbar__link" href="/lab/market">行情中心</a><button onClick={() => setImportOpen(true)}>导入 CSV</button><button onClick={() => setHoldingsOpen(true)}>券商持仓</button><div className="risk-appbar__status"><span className={data.dataMode === "api" && !marketUnavailable(data) ? "is-live" : "is-mock"}/><div><strong>{marketModeLabel(data)}</strong><small>{marketStatusDetail(data)}</small></div></div></div></header><main className="risk-main"><header className="risk-hero"><div><p>个人持仓风险监控与操作复盘</p><h1>先把风险算清楚，<br/><span>再解释今天发生了什么。</span></h1></div><div className="risk-hero__aside"><p>只读系统</p><strong>{data.riskEvents.length}</strong><span>个活跃风险事件</span><small>{data.portfolio.reliable ? "数据质量通过" : "可信度已降低"}</small></div></header>{view === "dashboard" && <Dashboard data={data} onEvidence={openEvidence} onNavigate={setView} onWorkflow={runWorkflow}/>} {view === "positions" && <Positions data={data} onSaveBroker={workspace.saveBrokerQuantity} onOpenHoldingsPaste={() => setHoldingsOpen(true)}/>} {view === "activity" && <Activity data={data} onEvidence={openEvidence}/>} {view === "review" && <Review data={data} onEvidence={openEvidence} onGenerate={workspace.generateReview} onSaveFeedback={workspace.saveFeedback} onMemoryStatus={workspace.setMemoryStatus} loading={workspace.reviewLoading} error={workspace.reviewError}/>} {view === "settings" && <Settings data={data} onMode={workspace.setMode} onImport={() => setImportOpen(true)} onClear={workspace.clear} onRestore={workspace.restoreMock} onExportBackup={workspace.exportBackup} onPreviewBackup={workspace.previewBackup} onRestoreBackup={workspace.restoreBackup}/>}</main><footer className="risk-footer"><span>zxlab / risk</span><p>确定性计算来自纯函数 Risk Engine；自然语言仅用于解释。</p><a href="/lab">返回 Lab</a></footer><EvidenceDrawer evidence={evidence} onClose={() => setSelectedEvidence(undefined)}/>{importOpen && <CsvImportDialog existingCount={data.transactions.length} preview={preview} mapping={mapping} onMapping={setMapping} onPreview={(text) => setCsvText(text)} onImport={async () => { if (!preview) return; await workspace.importTransactions(preview); setImportOpen(false); setCsvText(""); }} onClose={() => setImportOpen(false)}/>} {holdingsOpen && <HoldingsParseDialog loading={workspace.holdingsParseLoading} error={workspace.holdingsParseError} onParse={workspace.parseHoldingsDraft} onConfirm={workspace.confirmHoldingsDraft} onClose={() => setHoldingsOpen(false)}/>}</div>;
}
