import type { StatusActivity, StatusModule } from "./types.ts";

const ago = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();
const metric = (id: string, label: string, value: number | string, unit?: string, format?: "number" | "percentage" | "duration" | "bytes") => ({ id, label, value, unit, format, visibility: "authenticated" as const });

export const agentProvider = {
  async getStatus(): Promise<StatusModule> { const updatedAt = ago(0); return { id: "remote-agents", name: "Remote Agents", description: "Distributed development agents", category: "agent", status: "offline", summary: "2 / 3 agents online; windows-lab is awaiting a heartbeat.", updatedAt, visibility: "public", critical: false, metrics: [metric("online", "Online", "2 / 3"), metric("tasks", "Completed today", 51), metric("latency", "Median latency", 42, "ms", "duration")], details: { kind: "agent", agents: [
    { id: "macbook-neo", name: "macbook-neo", status: "operational", online: true, platform: "darwin-arm64", version: "0.1.0", lastHeartbeatAt: ago(.3), currentTask: { id: "idle", name: "idle", status: "completed" }, resources: { cpuPercent: 12, memoryPercent: 46, diskAvailableBytes: 182_000_000_000, latencyMs: 42 }, capabilities: ["shell", "filesystem", "git", "browser", "deploy"], taskStats: { completedToday: 14, failedToday: 1 } },
    { id: "cloud-runner", name: "cloud-runner", status: "operational", online: true, platform: "linux-amd64", version: "0.1.0", lastHeartbeatAt: ago(.52), currentTask: { id: "briefing-source-sync", name: "briefing-source-sync", status: "running", startedAt: ago(3.7) }, resources: { latencyMs: 54 }, capabilities: ["shell", "crawler", "git", "scheduled-task"], taskStats: { completedToday: 37, failedToday: 0 } },
    { id: "windows-lab", name: "windows-lab", status: "offline", online: false, platform: "windows-amd64", version: "0.1.0", lastHeartbeatAt: ago(360), capabilities: ["shell", "filesystem"], lastError: "heartbeat timeout" },
  ] } }; },
  async getActivities(): Promise<StatusActivity[]> { return [{ id: "agent-heartbeat", moduleId: "remote-agents", type: "heartbeat", title: "Heartbeat received from macbook-neo", status: "operational", createdAt: ago(.3), visibility: "authenticated" }, { id: "agent-task", moduleId: "remote-agents", type: "task_completed", title: "cloud-runner completed source crawl", status: "operational", createdAt: ago(8), visibility: "authenticated" }, { id: "agent-offline", moduleId: "remote-agents", type: "incident", title: "windows-lab heartbeat timed out", description: "Last contact was six hours ago.", status: "offline", createdAt: ago(360), visibility: "authenticated" }]; },
};

export const memoryProvider = { async getStatus(): Promise<StatusModule> { const updatedAt = ago(7); return { id: "memory", name: "Memory", description: "Ingestion, indexing, and recall", category: "memory", status: "degraded", summary: "Notes synchronization is delayed; recall remains available.", updatedAt, visibility: "public", critical: true, metrics: [metric("entries", "Entries", 2486), metric("queue", "Ingestion queue", 8), metric("recall-p95", "Recall p95", 231, "ms", "duration"), metric("storage", "Storage", 184_000_000, "B", "bytes")], incidents: [{ id: "notes-sync", title: "zxlab notes sync delayed", status: "identified", severity: "warning", startedAt: ago(19) }], details: { kind: "memory", memory: { freshness: "aging", lastSyncAt: ago(7), lastFullIndexAt: ago(120), lastError: "Notes source synchronization failed.", sources: ["ChatGPT conversations", "zxlab notes", "Briefing feedback", "GitHub activity", "Manual memories"].map((name, index) => ({ id: `source-${index}`, name, status: index === 1 ? "degraded" : "operational", updatedAt })) } } }; }, async getActivities(): Promise<StatusActivity[]> { return [{ id: "memory-index", moduleId: "memory", type: "index", title: "Memory indexed 37 new items", status: "operational", createdAt: ago(12), visibility: "authenticated" }, { id: "memory-sync", moduleId: "memory", type: "incident", title: "Notes source sync delayed", description: "Retry is pending in the ingestion queue.", status: "degraded", createdAt: ago(19), visibility: "authenticated" }]; } };

export const runtimeProvider = { async getStatus(): Promise<StatusModule> { const updatedAt = ago(1); return { id: "runtime", name: "zxlab Runtime", description: "Deployment, APIs, and scheduled work", category: "runtime", status: "operational", summary: "Production runtime and scheduled work are healthy.", updatedAt, visibility: "public", critical: true, metrics: [metric("version", "Version", "a8e4c71"), metric("api-p95", "API p95", 188, "ms", "duration"), metric("requests", "Requests / 24h", 4812), metric("error-rate", "Error rate", 0.18, "%", "percentage"), metric("uptime", "Uptime 7d", 99.96, "%", "percentage")], details: { kind: "runtime", runtime: { version: "a8e4c71", lastDeploymentAt: ago(34), lastSuccessfulCronAt: ago(11), services: [["Web frontend", "operational"], ["Status API", "operational"], ["LLM gateway", "operational"], ["Briefing pipeline", "operational"], ["Scheduled jobs", "operational"], ["Storage", "operational"]].map(([name, status], index) => ({ id: `runtime-${index}`, name, status: status as "operational", summary: "Healthy" })) } } }; }, async getActivities(): Promise<StatusActivity[]> { return [{ id: "runtime-deploy", moduleId: "runtime", type: "deploy", title: "zxlab deployed to production", status: "operational", createdAt: ago(34), visibility: "authenticated" }, { id: "runtime-recovery", moduleId: "runtime", type: "recovery", title: "Briefing pipeline recovered", description: "A brief delayed state cleared automatically.", status: "operational", createdAt: ago(47), visibility: "authenticated" }, { id: "runtime-cron", moduleId: "runtime", type: "sync", title: "Scheduled job completed", status: "operational", createdAt: ago(11), visibility: "authenticated" }]; } };
