from datetime import datetime
from typing import Protocol

from .models import MarketBar, MarketQuote


class MarketDataProvider(Protocol):
    async def get_quote(self, instrument_id: str) -> MarketQuote | None: ...
    async def get_quotes(self, instrument_ids: list[str]) -> list[MarketQuote]: ...
    async def get_bars(
        self, instrument_id: str, interval: str, start: datetime, end: datetime
    ) -> list[MarketBar]: ...
    async def get_market_status(self, exchange: str) -> str: ...
    async def health_check(self) -> dict[str, str]: ...
