export interface AgentRunView { id: string; workflow: string; status: string; createdAt: string; updatedAt: string; evidenceFingerprint: string | null; result?: { headline: string; summary: string; observations: Array<{ id: string; class: string; title: string; explanation: string; evidenceIds: string[] }>; limitations: string[] }; }
export interface AgentProfileView { profileId: string; watchlistRevision: string | null; bootstrap: "required" | "complete"; }
export interface AgentWatchlistItem { instrumentId: string; reason?: string; }
export class MarketAgentApiError extends Error { constructor(readonly code: string, message: string, readonly status: number) { super(message); this.name = "MarketAgentApiError"; } }
export async function getAgentRuns(): Promise<AgentRunView[]> { const response = await fetch("/api/private/market-agent/runs", { headers: { accept: "application/json" } }); if (!response.ok) throw new Error("Agent Runs 暂不可用"); const data = await response.json() as unknown; return Array.isArray(data) ? data as AgentRunView[] : Array.isArray((data as { runs?: unknown })?.runs) ? (data as { runs: AgentRunView[] }).runs : []; }
export async function getAgentProfile(): Promise<AgentProfileView> { const response = await fetch("/api/private/market-agent/profile", { headers: { accept: "application/json" } }); if (!response.ok) throw await apiError(response, "Profile 暂不可用"); return await response.json() as AgentProfileView; }
export async function syncAgentWatchlist(revision: string, items: AgentWatchlistItem[]): Promise<{ profile: AgentProfileView; watchlist: { revision: string; items: AgentWatchlistItem[] } }> { const response = await fetch("/api/private/market-agent/watchlist", { method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ revision, items }) }); if (!response.ok) throw await apiError(response, "观察列表同步失败"); return await response.json() as { profile: AgentProfileView; watchlist: { revision: string; items: AgentWatchlistItem[] } }; }
export async function startCloseReview(idempotencyKey = crypto.randomUUID()): Promise<{ runId: string; status: string }> { const response = await fetch("/api/private/market-agent/runs", { method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ workflow: "close_review", idempotencyKey }) }); if (!response.ok) throw await apiError(response, "盘后复盘暂不可用"); return await response.json() as { runId: string; status: string }; }
export async function sendRunFeedback(runId: string, value: "helpful" | "fact_error" | "missing_factor"): Promise<void> { const response = await fetch(`/api/private/market-agent/runs/${encodeURIComponent(runId)}/feedback`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ value }) }); if (!response.ok) throw new Error("反馈未保存"); }
export async function exportAgentRuns(): Promise<unknown> { const response = await fetch("/api/private/market-agent/export", { headers: { accept: "application/json" } }); if (!response.ok) throw await apiError(response, "记录导出失败"); return await response.json() as unknown; }
export async function deleteAgentRun(runId: string): Promise<void> { const response = await fetch(`/api/private/market-agent/runs/${encodeURIComponent(runId)}`, { method: "DELETE", headers: { accept: "application/json" } }); if (!response.ok) throw await apiError(response, "记录删除失败"); }

async function apiError(response: Response, fallback: string): Promise<MarketAgentApiError> {
  let value: unknown;
  try { value = await response.json(); } catch { value = null; }
  const error = value && typeof value === "object" ? (value as { error?: unknown }).error : null;
  const code = typeof error === "string" ? error : error && typeof error === "object" && typeof (error as { code?: unknown }).code === "string" ? String((error as { code: string }).code) : "MARKET_AGENT_UNAVAILABLE";
  const message = code === "WATCHLIST_BOOTSTRAP_REQUIRED" ? "请先确认并同步观察列表。" : fallback;
  return new MarketAgentApiError(code, message, response.status);
}
