export const MARKET_AGENT_GATEWAY_REQUEST_TIMEOUT_MS = 90_000;
export const MARKET_AGENT_GATEWAY_CALLS_PER_RUN = 2;
export const MARKET_AGENT_NON_GATEWAY_BUDGET_MS = 30_000;
export const MARKET_AGENT_LEASE_SAFETY_MARGIN_MS = 30_000;

export const MARKET_AGENT_RUN_LEASE_MS =
  MARKET_AGENT_GATEWAY_REQUEST_TIMEOUT_MS * MARKET_AGENT_GATEWAY_CALLS_PER_RUN
  + MARKET_AGENT_NON_GATEWAY_BUDGET_MS
  + MARKET_AGENT_LEASE_SAFETY_MARGIN_MS;

export const MARKET_AGENT_RUN_STREAM_GRACE_MS = 60_000;
export const MARKET_AGENT_RUN_STREAM_TIMEOUT_MS =
  MARKET_AGENT_RUN_LEASE_MS + MARKET_AGENT_RUN_STREAM_GRACE_MS;
