import type { SignalCategory, SignalSourceType } from "@zxlab/signal-schema";

export interface SignalSourceConfig {
  id: string;
  name: string;
  type: SignalSourceType;
  enabled: boolean;
  categoryHint: SignalCategory;
  priority: number;
  url?: string;
  repository?: string;
  query?: string;
  feed?: "topstories" | "newstories" | "beststories" | "showstories";
  includePrereleases?: boolean;
  requiresSecret?: string;
  topics?: string[];
  selectorPreset?: string;
  dedupGroup?: string;
  maxItemsPerRun: number;
  lookbackHours: number;
  tags: string[];
}

export const SIGNAL_SOURCES: readonly SignalSourceConfig[] = [
  {
    id: "cloudflare-developer-platform",
    name: "Cloudflare Developer Platform Changelog",
    type: "rss",
    enabled: true,
    categoryHint: "zxlab",
    priority: 100,
    url: "https://developers.cloudflare.com/changelog/rss/developer-platform.xml",
    maxItemsPerRun: 24,
    lookbackHours: 168,
    tags: ["cloudflare", "workers", "d1", "workflows", "ai-gateway"],
    dedupGroup: "cloudflare-platform",
  },
  {
    id: "github-workers-sdk-releases",
    name: "cloudflare/workers-sdk Releases",
    type: "github-release",
    enabled: true,
    categoryHint: "zxlab",
    priority: 90,
    repository: "cloudflare/workers-sdk",
    includePrereleases: false,
    maxItemsPerRun: 12,
    lookbackHours: 336,
    tags: ["cloudflare", "workers", "open-source", "sdk"],
    dedupGroup: "github-releases",
  },
  {
    id: "github-openai-node-releases",
    name: "openai/openai-node Releases",
    type: "github-release",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 85,
    repository: "openai/openai-node",
    includePrereleases: false,
    maxItemsPerRun: 12,
    lookbackHours: 336,
    tags: ["openai", "sdk", "api", "open-source"],
    dedupGroup: "github-releases",
  },
  {
    id: "github-openai-python-releases",
    name: "openai/openai-python Releases",
    type: "github-release",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 84,
    repository: "openai/openai-python",
    includePrereleases: false,
    maxItemsPerRun: 12,
    lookbackHours: 336,
    tags: ["openai", "sdk", "api", "open-source"],
    dedupGroup: "github-releases",
  },
  {
    id: "github-anthropic-sdk-typescript-releases",
    name: "anthropics/anthropic-sdk-typescript Releases",
    type: "github-release",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 82,
    repository: "anthropics/anthropic-sdk-typescript",
    includePrereleases: false,
    maxItemsPerRun: 12,
    lookbackHours: 336,
    tags: ["anthropic", "sdk", "api", "open-source"],
    dedupGroup: "github-releases",
  },
  {
    id: "github-google-genai-js-releases",
    name: "googleapis/js-genai Releases",
    type: "github-release",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 82,
    repository: "googleapis/js-genai",
    includePrereleases: false,
    maxItemsPerRun: 12,
    lookbackHours: 336,
    tags: ["google", "gemini", "sdk", "api", "open-source"],
    dedupGroup: "github-releases",
  },
  {
    id: "github-huggingface-transformers-releases",
    name: "huggingface/transformers Releases",
    type: "github-release",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 80,
    repository: "huggingface/transformers",
    includePrereleases: false,
    maxItemsPerRun: 12,
    lookbackHours: 336,
    tags: ["hugging-face", "model-runtime", "open-source"],
    dedupGroup: "github-releases",
  },
  {
    id: "github-huggingface-hub-releases",
    name: "huggingface/huggingface_hub Releases",
    type: "github-release",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 78,
    repository: "huggingface/huggingface_hub",
    includePrereleases: false,
    maxItemsPerRun: 12,
    lookbackHours: 336,
    tags: ["hugging-face", "hub", "open-source"],
    dedupGroup: "github-releases",
  },
  {
    id: "linuxdo-develop",
    name: "LinuxDo Develop RSS",
    type: "rss",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 58,
    url: "https://linuxdorss.longpink.com/summary/develop.xml",
    maxItemsPerRun: 16,
    lookbackHours: 72,
    tags: ["linuxdo", "community", "dev"],
    dedupGroup: "linuxdo",
  },
  {
    id: "linuxdo-news",
    name: "LinuxDo News RSS",
    type: "rss",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 56,
    url: "https://linuxdorss.longpink.com/summary/news.xml",
    maxItemsPerRun: 16,
    lookbackHours: 72,
    tags: ["linuxdo", "community", "news"],
    dedupGroup: "linuxdo",
  },
  {
    id: "linuxdo-resource",
    name: "LinuxDo Resource RSS",
    type: "rss",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 54,
    url: "https://linuxdorss.longpink.com/summary/resource.xml",
    maxItemsPerRun: 16,
    lookbackHours: 72,
    tags: ["linuxdo", "community", "resource"],
    dedupGroup: "linuxdo",
  },
  {
    id: "hn-ai-engineering",
    name: "Hacker News AI Engineering",
    type: "hacker-news",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 50,
    feed: "beststories",
    query: "agent,agents,llm,inference,benchmark,context,mcp,model api,ai infrastructure,tool use,cloudflare workers,devtools,developer tools",
    maxItemsPerRun: 6,
    lookbackHours: 48,
    tags: ["community", "discovery", "engineering"],
    dedupGroup: "community-ai-engineering",
  },
  {
    id: "hn-show-ai-engineering",
    name: "Hacker News Show AI Engineering",
    type: "hacker-news",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 45,
    feed: "showstories",
    query: "agent,agents,llm,inference,benchmark,context,mcp,model api,ai infrastructure,tool use,devtools,developer tools",
    maxItemsPerRun: 6,
    lookbackHours: 72,
    tags: ["community", "show-hn", "engineering"],
    dedupGroup: "community-ai-engineering",
  },
  {
    id: "arxiv-agent-infra",
    name: "arXiv Agents and AI Infrastructure",
    type: "arxiv",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 60,
    query: "(cat:cs.AI OR cat:cs.LG OR cat:cs.CL) AND (ti:agent OR abs:\"agent evaluation\" OR abs:benchmark OR abs:\"long context\" OR abs:\"tool use\" OR abs:inference OR abs:\"LLM\" OR abs:evaluation)",
    maxItemsPerRun: 24,
    lookbackHours: 168,
    tags: ["paper", "agent", "benchmark", "infra"],
    dedupGroup: "ai-research",
  },
  {
    id: "hf-daily-papers",
    name: "Hugging Face Daily Papers",
    type: "hf-daily-papers",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 62,
    maxItemsPerRun: 24,
    lookbackHours: 168,
    tags: ["paper", "hugging-face", "research"],
    dedupGroup: "ai-research",
  },
  {
    id: "producthunt-ai-devtools",
    name: "Product Hunt AI Devtools",
    type: "producthunt",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 42,
    requiresSecret: "PRODUCTHUNT_DEVELOPER_TOKEN",
    topics: ["Artificial Intelligence", "Developer Tools"],
    maxItemsPerRun: 20,
    lookbackHours: 72,
    tags: ["producthunt", "launch", "devtools", "ai"],
    dedupGroup: "product-launches",
  },
  {
    id: "openai-official-updates",
    name: "OpenAI Official Updates",
    type: "web-changelog",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 92,
    url: "https://developers.openai.com/resources/changelog/",
    selectorPreset: "official-update-links",
    maxItemsPerRun: 18,
    lookbackHours: 336,
    tags: ["openai", "official", "api"],
    dedupGroup: "official-ai-updates",
  },
  {
    id: "anthropic-official-updates",
    name: "Anthropic Claude Release Notes",
    type: "web-changelog",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 90,
    url: "https://platform.claude.com/docs/en/release-notes/overview",
    selectorPreset: "official-update-links",
    maxItemsPerRun: 18,
    lookbackHours: 336,
    tags: ["anthropic", "claude", "official", "api"],
    dedupGroup: "official-ai-updates",
  },
  {
    id: "google-gemini-official-updates",
    name: "Google Gemini API Changelog",
    type: "web-changelog",
    enabled: true,
    categoryHint: "ai-engineering",
    priority: 88,
    url: "https://ai.google.dev/gemini-api/docs/changelog",
    selectorPreset: "official-update-links",
    maxItemsPerRun: 18,
    lookbackHours: 336,
    tags: ["google", "gemini", "official", "api"],
    dedupGroup: "official-ai-updates",
  },
  {
    id: "market-a-share-news",
    name: "A-share Market News",
    type: "market-news",
    enabled: true,
    categoryHint: "markets",
    priority: 68,
    requiresSecret: "ZX_SIGNAL_MARKET_NEWS_URL",
    topics: ["SSE:510300", "SSE:588000", "SSE:513100"],
    maxItemsPerRun: 24,
    lookbackHours: 72,
    tags: ["markets", "a-share", "news"],
    dedupGroup: "a-share-market-news",
  },
] as const;

export function findSource(id: string): SignalSourceConfig | undefined {
  return SIGNAL_SOURCES.find((source) => source.id === id);
}
