import type { NewsItem } from "../game/types";

export const newsTemplates = [
  {
    id: "NEWS_TEMPLATE_MARKET_LIQUIDITY_WINDOW",
    title: "Interbank desks expect easier liquidity around the afternoon funding window",
    source: "market",
    scope: "market",
    polarity: 1,
    strength: 38,
    credibility: 72,
    durationDays: 1,
    remainingDays: 1,
    tags: ["liquidity", "macro", "risk-appetite"],
    heatImpact: 2
  },
  {
    id: "NEWS_TEMPLATE_MARKET_MARGIN_WARNING",
    title: "Brokerage notes flag crowded margin positions in recent high-beta leaders",
    source: "market",
    scope: "market",
    polarity: -1,
    strength: 42,
    credibility: 66,
    durationDays: 2,
    remainingDays: 2,
    tags: ["margin", "crowding", "risk"],
    heatImpact: 3
  },
  {
    id: "NEWS_TEMPLATE_MARKET_EXCHANGE_MONITORING",
    title: "Exchange monitoring notices mention abnormal intraday volatility across small caps",
    source: "policy",
    scope: "market",
    polarity: -1,
    strength: 48,
    credibility: 82,
    durationDays: 2,
    remainingDays: 2,
    tags: ["regulator", "small-cap", "volatility"],
    heatImpact: 5
  },
  {
    id: "NEWS_TEMPLATE_MARKET_LONG_ONLY_ROTATION",
    title: "Long-only funds are said to rebalance toward cash-generative defensives",
    source: "market",
    scope: "market",
    polarity: 0,
    strength: 32,
    credibility: 60,
    durationDays: 2,
    remainingDays: 2,
    tags: ["rotation", "institution", "defensive"],
    heatImpact: 1
  },
  {
    id: "NEWS_TEMPLATE_TECH_PROCUREMENT_CATALOG",
    title: "New procurement catalog draft gives extra scoring to domestic AI office platforms",
    source: "policy",
    scope: "sector",
    targetId: "tech",
    polarity: 1,
    strength: 62,
    credibility: 64,
    durationDays: 3,
    remainingDays: 3,
    tags: ["policy", "ai", "software"],
    heatImpact: 5
  },
  {
    id: "NEWS_TEMPLATE_TECH_CHIP_DELIVERY_DELAY",
    title: "Cloud integrators report another round of accelerator delivery delays",
    source: "market",
    scope: "sector",
    targetId: "tech",
    polarity: -1,
    strength: 36,
    credibility: 58,
    durationDays: 2,
    remainingDays: 2,
    tags: ["supply-chain", "ai", "hardware"],
    heatImpact: 3
  },
  {
    id: "NEWS_TEMPLATE_BIOTECH_FAST_REVIEW",
    title: "Hospital procurement pilots add a fast review lane for innovative diagnostics",
    source: "policy",
    scope: "sector",
    targetId: "biotech",
    polarity: 1,
    strength: 52,
    credibility: 68,
    durationDays: 3,
    remainingDays: 3,
    tags: ["policy", "diagnostics", "hospital"],
    heatImpact: 4
  },
  {
    id: "NEWS_TEMPLATE_BIOTECH_TRIAL_SAFETY",
    title: "Trial monitors ask several early-stage therapy programs for extra safety data",
    source: "market",
    scope: "sector",
    targetId: "biotech",
    polarity: -1,
    strength: 44,
    credibility: 61,
    durationDays: 2,
    remainingDays: 2,
    tags: ["clinical", "safety", "review"],
    heatImpact: 4
  },
  {
    id: "NEWS_TEMPLATE_PROPERTY_CITY_RELAXATION",
    title: "Two large cities quietly relax purchase restrictions for first-time buyers",
    source: "policy",
    scope: "sector",
    targetId: "property",
    polarity: 1,
    strength: 56,
    credibility: 63,
    durationDays: 3,
    remainingDays: 3,
    tags: ["property", "policy", "housing"],
    heatImpact: 4
  },
  {
    id: "NEWS_TEMPLATE_PROPERTY_BOND_EXTENSION",
    title: "A mid-sized developer seeks another bond extension after weak weekend sales",
    source: "market",
    scope: "sector",
    targetId: "property",
    polarity: -1,
    strength: 50,
    credibility: 74,
    durationDays: 2,
    remainingDays: 2,
    tags: ["credit", "developer", "sales"],
    heatImpact: 4
  },
  {
    id: "NEWS_TEMPLATE_CONSUMER_HOLIDAY_BOOKINGS",
    title: "Holiday booking channels show stronger premium snack and beverage demand",
    source: "market",
    scope: "sector",
    targetId: "consumer",
    polarity: 1,
    strength: 40,
    credibility: 69,
    durationDays: 2,
    remainingDays: 2,
    tags: ["consumer", "holiday", "sales"],
    heatImpact: 2
  },
  {
    id: "NEWS_TEMPLATE_CONSUMER_DISCOUNT_WAR",
    title: "Retail chains extend discount campaigns after private-label sales miss targets",
    source: "market",
    scope: "sector",
    targetId: "consumer",
    polarity: -1,
    strength: 34,
    credibility: 67,
    durationDays: 2,
    remainingDays: 2,
    tags: ["consumer", "discount", "margin"],
    heatImpact: 2
  },
  {
    id: "NEWS_TEMPLATE_RESOURCES_SMELTER_CURBS",
    title: "Smelters discuss coordinated maintenance after spot processing fees weaken",
    source: "market",
    scope: "sector",
    targetId: "resources",
    polarity: 1,
    strength: 46,
    credibility: 62,
    durationDays: 3,
    remainingDays: 3,
    tags: ["resources", "supply", "metals"],
    heatImpact: 3
  },
  {
    id: "NEWS_TEMPLATE_RESOURCES_IMPORT_QUOTA",
    title: "Import quota chatter pressures near-month industrial metal contracts",
    source: "rumor",
    scope: "sector",
    targetId: "resources",
    polarity: -1,
    strength: 38,
    credibility: 42,
    durationDays: 1,
    remainingDays: 1,
    tags: ["rumor", "quota", "metals"],
    heatImpact: 4
  },
  {
    id: "NEWS_TEMPLATE_FINANCE_CAPITAL_RULES",
    title: "Draft capital rules may give regional banks more room for small-business loans",
    source: "policy",
    scope: "sector",
    targetId: "finance",
    polarity: 1,
    strength: 36,
    credibility: 70,
    durationDays: 3,
    remainingDays: 3,
    tags: ["bank", "policy", "credit"],
    heatImpact: 2
  },
  {
    id: "NEWS_TEMPLATE_FINANCE_NIM_PRESSURE",
    title: "Deposit repricing stalls as banks defend customers with promotional rates",
    source: "market",
    scope: "sector",
    targetId: "finance",
    polarity: -1,
    strength: 32,
    credibility: 73,
    durationDays: 2,
    remainingDays: 2,
    tags: ["bank", "margin", "deposit"],
    heatImpact: 1
  },
  {
    id: "NEWS_TEMPLATE_DEFENSE_EXPORT_ORDER",
    title: "Defense equipment exporters receive inquiries tied to a regional fleet upgrade",
    source: "market",
    scope: "sector",
    targetId: "defense",
    polarity: 1,
    strength: 58,
    credibility: 55,
    durationDays: 2,
    remainingDays: 2,
    tags: ["defense", "export", "order"],
    heatImpact: 5
  },
  {
    id: "NEWS_TEMPLATE_DEFENSE_BUDGET_DELAY",
    title: "Budget approval for a surveillance systems package slips into next quarter",
    source: "policy",
    scope: "sector",
    targetId: "defense",
    polarity: -1,
    strength: 37,
    credibility: 71,
    durationDays: 2,
    remainingDays: 2,
    tags: ["defense", "budget", "delay"],
    heatImpact: 2
  },
  {
    id: "NEWS_TEMPLATE_ENERGY_GRID_STORAGE",
    title: "Grid planners add storage dispatch targets to the next capacity auction",
    source: "policy",
    scope: "sector",
    targetId: "energy",
    polarity: 1,
    strength: 50,
    credibility: 76,
    durationDays: 3,
    remainingDays: 3,
    tags: ["energy", "storage", "grid"],
    heatImpact: 3
  },
  {
    id: "NEWS_TEMPLATE_ENERGY_TARIFF_REVIEW",
    title: "A tariff review memo points to slower pass-through for distributed solar projects",
    source: "policy",
    scope: "sector",
    targetId: "energy",
    polarity: -1,
    strength: 43,
    credibility: 65,
    durationDays: 2,
    remainingDays: 2,
    tags: ["energy", "tariff", "solar"],
    heatImpact: 3
  },
  {
    id: "NEWS_TEMPLATE_DRAGON_SOFT_CONTRACT_RUMOR",
    title: "Trading rooms circulate a rumor that DragonSoft won a provincial workflow contract",
    source: "rumor",
    scope: "stock",
    targetId: "DRAGON_SOFT",
    polarity: 1,
    strength: 64,
    credibility: 38,
    durationDays: 1,
    remainingDays: 1,
    tags: ["rumor", "contract", "software"],
    heatImpact: 7
  },
  {
    id: "NEWS_TEMPLATE_CLOUDHARBOR_AI_CLARIFICATION",
    title: "CloudHarbor AI clarifies that a widely shared data-center order has not been signed",
    source: "clarification",
    scope: "stock",
    targetId: "CLOUDHARBOR_AI",
    polarity: -1,
    strength: 58,
    credibility: 88,
    durationDays: 1,
    remainingDays: 1,
    tags: ["clarification", "ai", "contract"],
    heatImpact: 6
  },
  {
    id: "NEWS_TEMPLATE_NEW_HORIZON_TRIAL_READOUT",
    title: "New Horizon Bio reports stronger-than-expected biomarker data in a small trial cohort",
    source: "financialReport",
    scope: "stock",
    targetId: "NEW_HORIZON_BIO",
    polarity: 1,
    strength: 70,
    credibility: 78,
    durationDays: 3,
    remainingDays: 3,
    tags: ["biotech", "trial", "data"],
    heatImpact: 6
  },
  {
    id: "NEWS_TEMPLATE_MIRROR_LAKE_REAGENT_SHORTAGE",
    title: "Mirror Lake Diagnostics distributors warn of reagent shortages in two provinces",
    source: "market",
    scope: "stock",
    targetId: "MIRROR_LAKE_MED",
    polarity: -1,
    strength: 46,
    credibility: 64,
    durationDays: 2,
    remainingDays: 2,
    tags: ["diagnostics", "supply-chain", "sales"],
    heatImpact: 4
  },
  {
    id: "NEWS_TEMPLATE_GOLDEN_ROOF_ASSET_SALE",
    title: "Golden Roof Properties is said to negotiate a mall asset sale to improve liquidity",
    source: "rumor",
    scope: "stock",
    targetId: "GOLDEN_ROOF",
    polarity: 1,
    strength: 48,
    credibility: 46,
    durationDays: 2,
    remainingDays: 2,
    tags: ["property", "asset-sale", "liquidity"],
    heatImpact: 4
  },
  {
    id: "NEWS_TEMPLATE_RED_RIVER_OFFTAKE",
    title: "Red River Lithium signs a non-binding offtake framework with a battery materials buyer",
    source: "market",
    scope: "stock",
    targetId: "RED_RIVER_LITHIUM",
    polarity: 1,
    strength: 60,
    credibility: 66,
    durationDays: 2,
    remainingDays: 2,
    tags: ["lithium", "offtake", "materials"],
    heatImpact: 5
  },
  {
    id: "NEWS_TEMPLATE_HARBOR_BANK_PROVISION",
    title: "Harbor Bank guides for higher credit provisions after a review of developer exposure",
    source: "financialReport",
    scope: "stock",
    targetId: "HARBOR_BANK",
    polarity: -1,
    strength: 45,
    credibility: 84,
    durationDays: 3,
    remainingDays: 3,
    tags: ["bank", "provision", "property"],
    heatImpact: 3
  },
  {
    id: "NEWS_TEMPLATE_NORTHSTAR_ROBOTICS_ORDER",
    title: "Northstar Robotics receives a repeat order from an automotive welding line customer",
    source: "market",
    scope: "stock",
    targetId: "NORTHSTAR_ROBOTICS",
    polarity: 1,
    strength: 54,
    credibility: 71,
    durationDays: 2,
    remainingDays: 2,
    tags: ["robotics", "order", "manufacturing"],
    heatImpact: 4
  }
] satisfies NewsItem[];
