import type { Stock, StockId } from "../game/types";
import { deriveInitialFundamentals } from "../game/fundamentals";
import { buildInitialDailyCandles } from "../game/charting";
import { createInitialShrimpCohorts } from "./shrimpCohorts";
import { deriveStockOptions } from "./stockOptions";

type StockTemplate = Omit<
  Stock,
  | "chart"
  | "dailyCandles"
  | "microPrice"
  | "microstructure"
  | "shrimpCohorts"
  | "options"
  | "boardQueueLedger"
  | "sharesOutstanding"
  | "fairPe"
  | "earningsPerShare"
  | "netProfit"
  | "profitGrowth"
>;

export const stockTemplates: Record<StockId, StockTemplate> = {
  DRAGON_SOFT: {
    id: "DRAGON_SOFT",
    name: "DragonSoft Systems",
    sector: "tech",
    boardType: "growth",
    price: 18.6,
    previousClose: 18.6,
    open: 18.6,
    high: 18.6,
    low: 18.6,
    marketCap: 10_200_000_000,
    floatShares: 300_000_000,
    baseLiquidity: 62_000_000,
    currentLiquidity: 62_000_000,
    turnover: 0,
    volume: 0,
    pe: 96,
    financialHealth: 48,
    sentiment: 62,
    attention: 66,
    momentum: 18,
    heat: 22,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 68,
      dipBuyers: 42,
      newsFollowers: 66,
      gamblers: 74,
      bagholders: 28,
      panicSellers: 22,
      greed: 64,
      fear: 26,
      attention: 66,
      boardFaith: 42
    },
    quantPresence: 58,
    institutionPresence: 22,
    avgHolderCost: 17.8,
    costDistribution: {
      deepProfit: 10,
      profit: 25,
      nearCost: 35,
      loss: 22,
      deepLoss: 8
    },
    activeModifiers: [],
    halted: false
  },
  NEW_HORIZON_BIO: {
    id: "NEW_HORIZON_BIO",
    name: "New Horizon Bio",
    sector: "biotech",
    boardType: "growth",
    price: 24.2,
    previousClose: 24.2,
    open: 24.2,
    high: 24.2,
    low: 24.2,
    marketCap: 13_500_000_000,
    floatShares: 260_000_000,
    baseLiquidity: 70_000_000,
    currentLiquidity: 70_000_000,
    turnover: 0,
    volume: 0,
    pe: 128,
    financialHealth: 44,
    sentiment: 55,
    attention: 52,
    momentum: 4,
    heat: 18,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 52,
      dipBuyers: 36,
      newsFollowers: 76,
      gamblers: 65,
      bagholders: 35,
      panicSellers: 28,
      greed: 55,
      fear: 34,
      attention: 52,
      boardFaith: 38
    },
    quantPresence: 48,
    institutionPresence: 28,
    avgHolderCost: 25.4,
    costDistribution: {
      deepProfit: 6,
      profit: 18,
      nearCost: 31,
      loss: 32,
      deepLoss: 13
    },
    activeModifiers: [],
    halted: false
  },
  GOLDEN_ROOF: {
    id: "GOLDEN_ROOF",
    name: "Golden Roof Properties",
    sector: "property",
    boardType: "main",
    price: 6.4,
    previousClose: 6.4,
    open: 6.4,
    high: 6.4,
    low: 6.4,
    marketCap: 9_800_000_000,
    floatShares: 800_000_000,
    baseLiquidity: 56_000_000,
    currentLiquidity: 56_000_000,
    turnover: 0,
    volume: 0,
    pe: 6.6,
    financialHealth: 31,
    sentiment: 36,
    attention: 58,
    momentum: -18,
    heat: 30,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 26,
      dipBuyers: 58,
      newsFollowers: 45,
      gamblers: 46,
      bagholders: 72,
      panicSellers: 48,
      greed: 32,
      fear: 58,
      attention: 58,
      boardFaith: 22
    },
    quantPresence: 34,
    institutionPresence: 18,
    avgHolderCost: 7.6,
    costDistribution: {
      deepProfit: 2,
      profit: 8,
      nearCost: 18,
      loss: 38,
      deepLoss: 26
    },
    activeModifiers: [],
    halted: false
  },
  PEARL_DAILY: {
    id: "PEARL_DAILY",
    name: "Pearl Daily Goods",
    sector: "consumer",
    boardType: "main",
    price: 38.5,
    previousClose: 38.5,
    open: 38.5,
    high: 38.5,
    low: 38.5,
    marketCap: 92_000_000_000,
    floatShares: 980_000_000,
    baseLiquidity: 210_000_000,
    currentLiquidity: 210_000_000,
    turnover: 0,
    volume: 0,
    pe: 34,
    financialHealth: 82,
    sentiment: 60,
    attention: 38,
    momentum: 5,
    heat: 6,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 34,
      dipBuyers: 62,
      newsFollowers: 39,
      gamblers: 18,
      bagholders: 22,
      panicSellers: 18,
      greed: 45,
      fear: 24,
      attention: 38,
      boardFaith: 35
    },
    quantPresence: 38,
    institutionPresence: 74,
    avgHolderCost: 37.2,
    costDistribution: {
      deepProfit: 8,
      profit: 28,
      nearCost: 46,
      loss: 15,
      deepLoss: 3
    },
    activeModifiers: [],
    halted: false
  },
  RED_RIVER_LITHIUM: {
    id: "RED_RIVER_LITHIUM",
    name: "Red River Lithium",
    sector: "resources",
    boardType: "main",
    price: 12.8,
    previousClose: 12.8,
    open: 12.8,
    high: 12.8,
    low: 12.8,
    marketCap: 21_500_000_000,
    floatShares: 510_000_000,
    baseLiquidity: 82_000_000,
    currentLiquidity: 82_000_000,
    turnover: 0,
    volume: 0,
    pe: 34,
    financialHealth: 57,
    sentiment: 55,
    attention: 49,
    momentum: 8,
    heat: 12,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 50,
      dipBuyers: 46,
      newsFollowers: 47,
      gamblers: 52,
      bagholders: 34,
      panicSellers: 30,
      greed: 52,
      fear: 32,
      attention: 49,
      boardFaith: 36
    },
    quantPresence: 46,
    institutionPresence: 42,
    avgHolderCost: 12.1,
    costDistribution: {
      deepProfit: 8,
      profit: 31,
      nearCost: 37,
      loss: 18,
      deepLoss: 6
    },
    activeModifiers: [],
    halted: false
  },
  HARBOR_BANK: {
    id: "HARBOR_BANK",
    name: "Harbor Commercial Bank",
    sector: "finance",
    boardType: "main",
    price: 5.15,
    previousClose: 5.15,
    open: 5.15,
    high: 5.15,
    low: 5.15,
    marketCap: 210_000_000_000,
    floatShares: 18_000_000_000,
    baseLiquidity: 330_000_000,
    currentLiquidity: 330_000_000,
    turnover: 0,
    volume: 0,
    pe: 8.8,
    financialHealth: 76,
    sentiment: 48,
    attention: 28,
    momentum: -2,
    heat: 3,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 18,
      dipBuyers: 54,
      newsFollowers: 28,
      gamblers: 10,
      bagholders: 30,
      panicSellers: 18,
      greed: 30,
      fear: 28,
      attention: 28,
      boardFaith: 24
    },
    quantPresence: 22,
    institutionPresence: 84,
    avgHolderCost: 5.22,
    costDistribution: {
      deepProfit: 2,
      profit: 16,
      nearCost: 60,
      loss: 18,
      deepLoss: 4
    },
    activeModifiers: [],
    halted: false
  },
  SKY_SHIELD: {
    id: "SKY_SHIELD",
    name: "Sky Shield Systems",
    sector: "defense",
    boardType: "main",
    price: 16.75,
    previousClose: 16.75,
    open: 16.75,
    high: 16.75,
    low: 16.75,
    marketCap: 17_200_000_000,
    floatShares: 260_000_000,
    baseLiquidity: 66_000_000,
    currentLiquidity: 66_000_000,
    turnover: 0,
    volume: 0,
    pe: 58,
    financialHealth: 61,
    sentiment: 60,
    attention: 63,
    momentum: 14,
    heat: 16,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 58,
      dipBuyers: 40,
      newsFollowers: 58,
      gamblers: 62,
      bagholders: 26,
      panicSellers: 24,
      greed: 58,
      fear: 30,
      attention: 63,
      boardFaith: 40
    },
    quantPresence: 50,
    institutionPresence: 36,
    avgHolderCost: 15.9,
    costDistribution: {
      deepProfit: 6,
      profit: 33,
      nearCost: 39,
      loss: 17,
      deepLoss: 5
    },
    activeModifiers: [],
    halted: false
  },
  EAST_GRID_ENERGY: {
    id: "EAST_GRID_ENERGY",
    name: "East Grid Energy",
    sector: "energy",
    boardType: "main",
    price: 9.7,
    previousClose: 9.7,
    open: 9.7,
    high: 9.7,
    low: 9.7,
    marketCap: 68_000_000_000,
    floatShares: 4_200_000_000,
    baseLiquidity: 175_000_000,
    currentLiquidity: 175_000_000,
    turnover: 0,
    volume: 0,
    pe: 17,
    financialHealth: 79,
    sentiment: 54,
    attention: 34,
    momentum: 1,
    heat: 4,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 25,
      dipBuyers: 57,
      newsFollowers: 34,
      gamblers: 18,
      bagholders: 24,
      panicSellers: 20,
      greed: 36,
      fear: 26,
      attention: 34,
      boardFaith: 27
    },
    quantPresence: 28,
    institutionPresence: 72,
    avgHolderCost: 9.45,
    costDistribution: {
      deepProfit: 5,
      profit: 24,
      nearCost: 50,
      loss: 17,
      deepLoss: 4
    },
    activeModifiers: [],
    halted: false
  },
  CLOUDHARBOR_AI: {
    id: "CLOUDHARBOR_AI",
    name: "CloudHarbor AI",
    sector: "tech",
    boardType: "growth",
    price: 31.4,
    previousClose: 31.4,
    open: 31.4,
    high: 31.4,
    low: 31.4,
    marketCap: 28_500_000_000,
    floatShares: 360_000_000,
    baseLiquidity: 96_000_000,
    currentLiquidity: 96_000_000,
    turnover: 0,
    volume: 0,
    pe: 72,
    financialHealth: 63,
    sentiment: 59,
    attention: 57,
    momentum: 7,
    heat: 12,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 58,
      dipBuyers: 38,
      newsFollowers: 64,
      gamblers: 62,
      bagholders: 26,
      panicSellers: 24,
      greed: 56,
      fear: 30,
      attention: 57,
      boardFaith: 39
    },
    quantPresence: 62,
    institutionPresence: 39,
    avgHolderCost: 30.2,
    costDistribution: {
      deepProfit: 7,
      profit: 28,
      nearCost: 41,
      loss: 18,
      deepLoss: 6
    },
    activeModifiers: [],
    halted: false
  },
  MIRROR_LAKE_MED: {
    id: "MIRROR_LAKE_MED",
    name: "Mirror Lake Diagnostics",
    sector: "biotech",
    boardType: "growth",
    price: 18.9,
    previousClose: 18.9,
    open: 18.9,
    high: 18.9,
    low: 18.9,
    marketCap: 16_800_000_000,
    floatShares: 310_000_000,
    baseLiquidity: 78_000_000,
    currentLiquidity: 78_000_000,
    turnover: 0,
    volume: 0,
    pe: 88,
    financialHealth: 54,
    sentiment: 51,
    attention: 46,
    momentum: -3,
    heat: 9,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 44,
      dipBuyers: 43,
      newsFollowers: 72,
      gamblers: 58,
      bagholders: 33,
      panicSellers: 30,
      greed: 48,
      fear: 36,
      attention: 46,
      boardFaith: 34
    },
    quantPresence: 51,
    institutionPresence: 34,
    avgHolderCost: 19.6,
    costDistribution: {
      deepProfit: 4,
      profit: 19,
      nearCost: 38,
      loss: 29,
      deepLoss: 10
    },
    activeModifiers: [],
    halted: false
  },
  SILVER_PINES_SOLAR: {
    id: "SILVER_PINES_SOLAR",
    name: "Silver Pines Solar",
    sector: "energy",
    boardType: "main",
    price: 11.6,
    previousClose: 11.6,
    open: 11.6,
    high: 11.6,
    low: 11.6,
    marketCap: 24_000_000_000,
    floatShares: 1_050_000_000,
    baseLiquidity: 88_000_000,
    currentLiquidity: 88_000_000,
    turnover: 0,
    volume: 0,
    pe: 28,
    financialHealth: 56,
    sentiment: 49,
    attention: 43,
    momentum: -2,
    heat: 7,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 39,
      dipBuyers: 50,
      newsFollowers: 41,
      gamblers: 36,
      bagholders: 38,
      panicSellers: 31,
      greed: 43,
      fear: 37,
      attention: 43,
      boardFaith: 30
    },
    quantPresence: 43,
    institutionPresence: 46,
    avgHolderCost: 11.9,
    costDistribution: {
      deepProfit: 5,
      profit: 20,
      nearCost: 42,
      loss: 25,
      deepLoss: 8
    },
    activeModifiers: [],
    halted: false
  },
  NORTHSTAR_ROBOTICS: {
    id: "NORTHSTAR_ROBOTICS",
    name: "Northstar Robotics",
    sector: "defense",
    boardType: "main",
    price: 22.8,
    previousClose: 22.8,
    open: 22.8,
    high: 22.8,
    low: 22.8,
    marketCap: 34_500_000_000,
    floatShares: 640_000_000,
    baseLiquidity: 104_000_000,
    currentLiquidity: 104_000_000,
    turnover: 0,
    volume: 0,
    pe: 46,
    financialHealth: 66,
    sentiment: 60,
    attention: 61,
    momentum: 10,
    heat: 14,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 62,
      dipBuyers: 42,
      newsFollowers: 55,
      gamblers: 55,
      bagholders: 24,
      panicSellers: 23,
      greed: 57,
      fear: 28,
      attention: 61,
      boardFaith: 42
    },
    quantPresence: 54,
    institutionPresence: 48,
    avgHolderCost: 21.7,
    costDistribution: {
      deepProfit: 8,
      profit: 30,
      nearCost: 40,
      loss: 17,
      deepLoss: 5
    },
    activeModifiers: [],
    halted: false
  },
  RIVERSTONE_CEMENT: {
    id: "RIVERSTONE_CEMENT",
    name: "Riverstone Cement",
    sector: "property",
    boardType: "main",
    price: 7.85,
    previousClose: 7.85,
    open: 7.85,
    high: 7.85,
    low: 7.85,
    marketCap: 18_800_000_000,
    floatShares: 1_300_000_000,
    baseLiquidity: 72_000_000,
    currentLiquidity: 72_000_000,
    turnover: 0,
    volume: 0,
    pe: 10.5,
    financialHealth: 47,
    sentiment: 39,
    attention: 36,
    momentum: -8,
    heat: 8,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 31,
      dipBuyers: 49,
      newsFollowers: 35,
      gamblers: 29,
      bagholders: 46,
      panicSellers: 37,
      greed: 36,
      fear: 43,
      attention: 36,
      boardFaith: 24
    },
    quantPresence: 32,
    institutionPresence: 40,
    avgHolderCost: 8.15,
    costDistribution: {
      deepProfit: 3,
      profit: 15,
      nearCost: 43,
      loss: 29,
      deepLoss: 10
    },
    activeModifiers: [],
    halted: false
  },
  ORCHID_SNACKS: {
    id: "ORCHID_SNACKS",
    name: "Orchid Snacks",
    sector: "consumer",
    boardType: "main",
    price: 26.2,
    previousClose: 26.2,
    open: 26.2,
    high: 26.2,
    low: 26.2,
    marketCap: 42_000_000_000,
    floatShares: 520_000_000,
    baseLiquidity: 122_000_000,
    currentLiquidity: 122_000_000,
    turnover: 0,
    volume: 0,
    pe: 32,
    financialHealth: 74,
    sentiment: 56,
    attention: 40,
    momentum: 3,
    heat: 6,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 33,
      dipBuyers: 58,
      newsFollowers: 42,
      gamblers: 24,
      bagholders: 21,
      panicSellers: 18,
      greed: 44,
      fear: 27,
      attention: 40,
      boardFaith: 31
    },
    quantPresence: 36,
    institutionPresence: 65,
    avgHolderCost: 25.3,
    costDistribution: {
      deepProfit: 7,
      profit: 27,
      nearCost: 47,
      loss: 16,
      deepLoss: 3
    },
    activeModifiers: [],
    halted: false
  },
  WESTERN_CLOUD_BANK: {
    id: "WESTERN_CLOUD_BANK",
    name: "Western Cloud Bank",
    sector: "finance",
    boardType: "main",
    price: 8.6,
    previousClose: 8.6,
    open: 8.6,
    high: 8.6,
    low: 8.6,
    marketCap: 78_000_000_000,
    floatShares: 5_800_000_000,
    baseLiquidity: 185_000_000,
    currentLiquidity: 185_000_000,
    turnover: 0,
    volume: 0,
    pe: 9.2,
    financialHealth: 61,
    sentiment: 47,
    attention: 30,
    momentum: -2,
    heat: 4,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 20,
      dipBuyers: 50,
      newsFollowers: 27,
      gamblers: 12,
      bagholders: 31,
      panicSellers: 22,
      greed: 30,
      fear: 31,
      attention: 30,
      boardFaith: 23
    },
    quantPresence: 24,
    institutionPresence: 78,
    avgHolderCost: 8.75,
    costDistribution: {
      deepProfit: 3,
      profit: 17,
      nearCost: 56,
      loss: 20,
      deepLoss: 4
    },
    activeModifiers: [],
    halted: false
  },
  COPPER_CROWN_MINING: {
    id: "COPPER_CROWN_MINING",
    name: "Copper Crown Mining",
    sector: "resources",
    boardType: "main",
    price: 14.3,
    previousClose: 14.3,
    open: 14.3,
    high: 14.3,
    low: 14.3,
    marketCap: 31_000_000_000,
    floatShares: 880_000_000,
    baseLiquidity: 112_000_000,
    currentLiquidity: 112_000_000,
    turnover: 0,
    volume: 0,
    pe: 24,
    financialHealth: 58,
    sentiment: 53,
    attention: 45,
    momentum: 5,
    heat: 9,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 48,
      dipBuyers: 47,
      newsFollowers: 44,
      gamblers: 45,
      bagholders: 33,
      panicSellers: 29,
      greed: 48,
      fear: 34,
      attention: 45,
      boardFaith: 33
    },
    quantPresence: 44,
    institutionPresence: 50,
    avgHolderCost: 13.9,
    costDistribution: {
      deepProfit: 6,
      profit: 25,
      nearCost: 43,
      loss: 20,
      deepLoss: 6
    },
    activeModifiers: [],
    halted: false
  }
};

export function createStocks(): Record<StockId, Stock> {
  return Object.fromEntries(
    Object.entries(stockTemplates).map(([id, stock]) => {
      const fundamentals = deriveInitialFundamentals(stock);

      const initializedStock: Stock = {
        ...stock,
        ...fundamentals,
        microPrice: stock.price,
        microstructure: {
          flowMemory: 0,
          liquidityStress: 0,
          shockMemory: 0,
          lastPrintSign: 0
        },
        options: deriveStockOptions(stock),
        boardQueueLedger: {
          buy: {
            quality: 0,
            dominantSource: "mixed",
            addedNotional: 0,
            consumedNotional: 0,
            lockedTicks: 0,
            openedTicks: 0
          },
          sell: {
            quality: 0,
            dominantSource: "mixed",
            addedNotional: 0,
            consumedNotional: 0,
            lockedTicks: 0,
            openedTicks: 0
          }
        },
        shrimpCohorts: createInitialShrimpCohorts(stock),
        retail: { ...stock.retail },
        costDistribution: { ...stock.costDistribution },
        activeModifiers: [...stock.activeModifiers],
        chart: [
          {
            day: 1,
            tick: 0,
            price: stock.price,
            boardState: stock.boardState
          }
        ],
        dailyCandles: []
      };
      initializedStock.dailyCandles = buildInitialDailyCandles(initializedStock);

      return [id, initializedStock];
    })
  ) as Record<StockId, Stock>;
}
