import type { Stock, StockId, Whale } from "../game/types";
import { initializeWhaleAccounting } from "../simulation/whaleAccounting";

export function createWhales(stocks: Record<StockId, Stock>): Whale[] {
  const whales: Whale[] = [
    {
      id: "WHALE_PUMP_LORD",
      name: "North Tower Capital",
      archetype: "pumpLord",
      cash: 280_000_000,
      positions: {},
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 280_000_000,
      aggression: 78,
      patience: 48,
      riskTolerance: 72,
      heatTolerance: 58,
      preferredCaps: ["small", "mid"],
      preferredSectors: ["tech", "defense", "biotech"],
      intention: "idle",
      nextActionTick: 0,
      strategyNote: "Accumulates story stocks, tries to seal boards, exits high-heat pumps."
    },
    {
      id: "WHALE_QUANT_KNIFE",
      name: "Silver Needle Quant",
      archetype: "quantKnife",
      cash: 350_000_000,
      positions: {
        DRAGON_SOFT: 900_000,
        GOLDEN_ROOF: 2_200_000,
        SKY_SHIELD: 750_000,
        RED_RIVER_LITHIUM: 1_100_000,
        CLOUDHARBOR_AI: 520_000,
        NORTHSTAR_ROBOTICS: 460_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 350_000_000,
      aggression: 66,
      patience: 35,
      riskTolerance: 62,
      heatTolerance: 72,
      preferredCaps: ["small", "mid", "large"],
      preferredSectors: ["tech", "resources", "defense"],
      intention: "idle",
      nextActionTick: 0,
      strategyNote: "Attacks weak boards and crowded pumps, but buys panic reversals."
    },
    {
      id: "WHALE_VALUE_WALL",
      name: "Stone Harbor Fund",
      archetype: "valueWall",
      cash: 620_000_000,
      positions: {
        PEARL_DAILY: 2_000_000,
        HARBOR_BANK: 8_000_000,
        EAST_GRID_ENERGY: 3_500_000,
        RED_RIVER_LITHIUM: 780_000,
        ORCHID_SNACKS: 1_100_000,
        WESTERN_CLOUD_BANK: 4_000_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 620_000_000,
      aggression: 36,
      patience: 82,
      riskTolerance: 44,
      heatTolerance: 34,
      preferredCaps: ["large"],
      preferredSectors: ["consumer", "finance", "energy"],
      intention: "idle",
      nextActionTick: 0,
      strategyNote: "Long-horizon large-cap holder, buys quality dips and sells exuberance."
    },
    {
      id: "WHALE_RESCUE",
      name: "Blue Anchor Holdings",
      archetype: "rescueWhale",
      cash: 900_000_000,
      positions: {
        RED_RIVER_LITHIUM: 520_000,
        WESTERN_CLOUD_BANK: 3_200_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 900_000_000,
      aggression: 30,
      patience: 74,
      riskTolerance: 38,
      heatTolerance: 80,
      preferredCaps: ["large"],
      preferredSectors: ["finance", "energy", "consumer"],
      intention: "idle",
      nextActionTick: 0,
      strategyNote: "Supports large caps during weak markets and trims after recovery."
    },
    {
      id: "WHALE_BAGHOLDER",
      name: "Everbright Ladder Desk",
      archetype: "bagholderWhale",
      cash: 120_000_000,
      positions: {
        GOLDEN_ROOF: 12_000_000,
        NEW_HORIZON_BIO: 1_400_000,
        RIVERSTONE_CEMENT: 2_800_000,
        MIRROR_LAKE_MED: 520_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 120_000_000,
      aggression: 62,
      patience: 28,
      riskTolerance: 50,
      heatTolerance: 44,
      preferredCaps: ["small", "mid"],
      preferredSectors: ["property", "biotech"],
      intention: "idle",
      nextActionTick: 0,
      strategyNote: "Creates support when trapped, then sells into player or retail demand."
    },
    {
      id: "WHALE_SECTOR_ROTATOR",
      name: "Red Kite Rotation",
      archetype: "sectorRotator",
      cash: 420_000_000,
      positions: {
        RED_RIVER_LITHIUM: 900_000,
        SKY_SHIELD: 550_000,
        COPPER_CROWN_MINING: 1_100_000,
        SILVER_PINES_SOLAR: 1_300_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 420_000_000,
      aggression: 58,
      patience: 54,
      riskTolerance: 60,
      heatTolerance: 52,
      preferredCaps: ["mid", "large"],
      preferredSectors: ["resources", "defense", "tech", "energy"],
      intention: "idle",
      nextActionTick: 1,
      strategyNote: "Rotates into hot sectors and exits when attention or heat rolls over."
    },
    {
      id: "WHALE_LIQUIDITY_VULTURE",
      name: "Black Shoal Partners",
      archetype: "liquidityVulture",
      cash: 260_000_000,
      positions: {
        GOLDEN_ROOF: 1_200_000,
        NEW_HORIZON_BIO: 450_000,
        RED_RIVER_LITHIUM: 360_000,
        RIVERSTONE_CEMENT: 1_500_000,
        MIRROR_LAKE_MED: 260_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 260_000_000,
      aggression: 52,
      patience: 64,
      riskTolerance: 68,
      heatTolerance: 46,
      preferredCaps: ["small", "mid"],
      preferredSectors: ["property", "biotech", "resources"],
      intention: "idle",
      nextActionTick: 2,
      strategyNote: "Scoops panic liquidity and sells rebounds into crowded demand."
    },
    {
      id: "WHALE_MOMENTUM_RAIDER",
      name: "Copper Gate Raiders",
      archetype: "quantKnife",
      cash: 240_000_000,
      positions: {
        RED_RIVER_LITHIUM: 700_000,
        DRAGON_SOFT: 420_000,
        PEARL_DAILY: 260_000,
        CLOUDHARBOR_AI: 360_000,
        COPPER_CROWN_MINING: 620_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 240_000_000,
      aggression: 82,
      patience: 22,
      riskTolerance: 66,
      heatTolerance: 68,
      preferredCaps: ["small", "mid"],
      preferredSectors: ["resources", "tech", "defense", "energy"],
      intention: "idle",
      nextActionTick: 1,
      strategyNote: "Fades overextended multi-day runs and joins fast stop-loss cascades."
    },
    {
      id: "WHALE_THEME_ENGINE",
      name: "Jade Mountain Themes",
      archetype: "pumpLord",
      cash: 320_000_000,
      positions: {
        RED_RIVER_LITHIUM: 620_000,
        SKY_SHIELD: 360_000,
        CLOUDHARBOR_AI: 280_000,
        NORTHSTAR_ROBOTICS: 300_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 320_000_000,
      aggression: 72,
      patience: 44,
      riskTolerance: 70,
      heatTolerance: 54,
      preferredCaps: ["small", "mid"],
      preferredSectors: ["resources", "biotech", "defense", "tech"],
      intention: "idle",
      nextActionTick: 2,
      strategyNote: "Runs short theme campaigns, then returns after shakeouts instead of vanishing."
    },
    {
      id: "WHALE_DEEP_VALUE",
      name: "Cedar Basin Value",
      archetype: "valueWall",
      cash: 520_000_000,
      positions: {
        EAST_GRID_ENERGY: 2_600_000,
        HARBOR_BANK: 5_500_000,
        PEARL_DAILY: 900_000,
        RED_RIVER_LITHIUM: 640_000,
        ORCHID_SNACKS: 700_000,
        SILVER_PINES_SOLAR: 900_000,
        COPPER_CROWN_MINING: 550_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 520_000_000,
      aggression: 42,
      patience: 78,
      riskTolerance: 52,
      heatTolerance: 40,
      preferredCaps: ["mid", "large"],
      preferredSectors: ["energy", "finance", "consumer", "resources"],
      intention: "idle",
      nextActionTick: 3,
      strategyNote: "Absorbs quality washouts and supplies expensive multi-day rallies."
    },
    {
      id: "WHALE_RESCUE_TWO",
      name: "Harbor Stabilization Desk",
      archetype: "rescueWhale",
      cash: 760_000_000,
      positions: {
        RED_RIVER_LITHIUM: 560_000,
        SKY_SHIELD: 300_000,
        WESTERN_CLOUD_BANK: 2_400_000,
        ORCHID_SNACKS: 520_000
      },
      avgCostByStock: {},
      realizedPnl: 0,
      unrealizedPnl: 0,
      netWorth: 760_000_000,
      aggression: 38,
      patience: 68,
      riskTolerance: 46,
      heatTolerance: 84,
      preferredCaps: ["large"],
      preferredSectors: ["finance", "energy", "consumer"],
      intention: "idle",
      nextActionTick: 4,
      strategyNote: "Adds delayed support only after real stress and visible absorption."
    }
  ];

  return whales.map((whale) => initializeWhaleAccounting(whale, stocks));
}
