/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.beta.jsonc --include-runtime=false --strict-vars=false` (hash: e1106653eee750a501233574c3947899)
interface __BaseEnv_Env {
	DB: D1Database;
	MARKET_AGENT_RUNS: Queue;
	MARKET_AGENT_GENERATION_ENABLED: string;
	MARKET_AGENT_GATEWAY_URL: string;
	MARKET_AGENT_MAX_RECOVERY_GENERATIONS: string;
	MARKET_AGENT_RUN_RETENTION_DAYS: string;
	COMPANY_UPDATE_RESEARCH_ENABLED: string;
	FINANCIAL_TOOL_RUNTIME_MODE: string;
	RESEARCH_DOSSIER_PROJECTOR_MODE: string;
	MARKET_AGENT_GATEWAY_TOKEN: string;
	MARKET_AGENT_PROXY_TOKEN: string;
	ZX_RUNTIME_SERVICE_TOKEN: string;
	MARKET_AGENT_MEMORY_TOKEN: string;
	MARKET_RESEARCH_TOKEN: string;
	MARKET_SNAPSHOT_SERVICE: Fetcher /* zxlab-risk-market-beta */;
	SIGNAL_MEMORY_SERVICE: Fetcher /* zx-signal */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MARKET_AGENT_GENERATION_ENABLED" | "MARKET_AGENT_GATEWAY_URL" | "MARKET_AGENT_MAX_RECOVERY_GENERATIONS" | "MARKET_AGENT_RUN_RETENTION_DAYS" | "COMPANY_UPDATE_RESEARCH_ENABLED" | "FINANCIAL_TOOL_RUNTIME_MODE" | "RESEARCH_DOSSIER_PROJECTOR_MODE" | "MARKET_AGENT_GATEWAY_TOKEN" | "MARKET_AGENT_PROXY_TOKEN" | "ZX_RUNTIME_SERVICE_TOKEN" | "MARKET_AGENT_MEMORY_TOKEN" | "MARKET_RESEARCH_TOKEN">> {}
}
